const ar = {
  // Admissions & Students
  admission: 'القبول',
  applicant: 'المتقدم',
  student: 'الطالب',
  student_id: 'الرقم الجامعي',
  enrollment: 'التسجيل / الالتحاق',
  transfer: 'التحويل',
  withdrawal: 'الانسحاب',
  graduate: 'الخريج',

  // Academic Structure
  faculty_college: 'الكلية',
  department: 'القسم',
  program_major: 'التخصص',
  course: 'المقرر',
  credit_hours: 'الساعات المعتمدة',
  semester: 'الفصل الدراسي',
  academic_year: 'العام الدراسي',
  prerequisite: 'المتطلب السابق',
  syllabus: 'توصيف المقرر',
  study_plan: 'الخطة الدراسية',

  // Registration & Timetable
  course_registration: 'تسجيل المقررات',
  add_drop: 'الحذف والإضافة',
  section: 'الشعبة',
  timetable: 'الجدول الدراسي',
  lecture_hall: 'قاعة المحاضرات',
  attendance: 'الحضور',
  absence: 'الغياب',
  academic_advisor: 'المرشد الأكاديمي',

  // Exams & Grades
  exam: 'الاختبار',
  midterm: 'الاختبار النصفي',
  final_exam: 'الاختبار النهائي',
  grade: 'الدرجة',
  gpa: 'المعدل التراكمي',
  semester_gpa: 'المعدل الفصلي',
  transcript: 'كشف الدرجات',
  academic_probation: 'الإنذار الأكاديمي',
  incomplete: 'غير مكتمل',
  result: 'النتيجة',

  // Faculty & HR
  instructor_lecturer: 'المحاضر',
  professor: 'الأستاذ',
  teaching_assistant: 'المعيد',
  employee: 'الموظف',
  payroll: 'الرواتب',
  leave: 'الإجازة',
  contract: 'العقد',
  job_title: 'المسمى الوظيفي',

  // Finance
  tuition_fees: 'الرسوم الدراسية',
  invoice: 'الفاتورة',
  payment: 'الدفع',
  scholarship: 'المنحة الدراسية',
  discount: 'الخصم',
  refund: 'الاسترداد',
  budget: 'الميزانية',
  receipt: 'الإيصال',

  // Library & Services
  library: 'المكتبة',
  borrowing: 'الاستعارة',
  housing_dormitory: 'السكن الجامعي',
  certificate: 'الشهادة',
  graduation_clearance: 'إخلاء الطرف',

  // System / General
  dashboard: 'لوحة التحكم',
  user: 'المستخدم',
  role: 'الدور',
  permission: 'الصلاحية',
  report: 'التقرير',
  notification: 'الإشعار',
  settings: 'الإعدادات',
  login: 'تسجيل الدخول',
  search: 'بحث',
  save: 'حفظ',
  cancel: 'إلغاء',
  delete: 'حذف',

  // Admin Dashboard
  admin_dashboard: 'لوحة إدارة الجامعة',
  system_active: 'النشط',
  overview_metrics: 'نظرة عامة على المؤشرات الرئيسية والنشاط الأخير في الجامعة.',
  register_student: 'تسجيل طالب',
  admissions_queue: 'قائمة القبول',
  analytics: 'التحليلات',
  total_enrollment: 'إجمالي التسجيل',
  actively_enrolled: 'مسجلين بشكل نشط',
  academic_faculty: 'الهيئة الأكاديمية',
  on_active_teaching: 'في التدريس النشط',
  total_programs: 'إجمالي البرامج',
  active_courses: 'المقررات النشطة',
  total_collected: 'إجمالي المحصّل',
  collection_rate: 'معدل التحصيل',
  outstanding_fees: 'الرسوم المستحقة',
  pending_clearance: 'معلق لإخلاء الطرف',
  pending_admissions: 'القبول المعلق',
  total_applied: 'إجمالي المتقدمين',
  active_teaching: 'التدريس النشط',
  total_sections: 'إجمالي الأقسام',
  graduated_alumni: 'الخريجين',
  issued_certs: 'الشهادات الصادرة',
  student_status_distribution: 'توزيع حالة الطلاب',
  total: 'الإجمالي',
  enrollment_lifecycle: 'تفصيل دورة حياة التسجيل عبر جميع الأقسام',
  enrolled: 'مسجل',
  pending: 'معلق',
  suspended: 'موقوف',
  graduated: 'خريج',
  open_student_directory: 'فتح دليل الطلاب',
  tuition_fees_health: 'صحة الرسوم الدراسية',
  collected: 'محصّل',
  invoiced_totals: 'إجمالي الفواتير مقابل مدفوعات الطلاب المحصّلة',
  collection_progress: 'تقدم التحصيل',
  total_invoiced: 'إجمالي الفواتير',
  cleared_payments: 'المدفوعات المحصّلة',
  outstanding_balance: 'الرصيد المستحق',
  view_detailed_ledger: 'عرض السجل التفصيلي',
  admissions_funnel: 'قمع القبول',
  candidates: 'المرشحين',
  applicant_flow: 'تدفق المتقدمين الجدد وتحويلهم إلى طلاب مسجلين',
  pending_review: 'قيد المراجعة',
  approved_offers: 'العروض المعتمدة',
  enrolled_students: 'الطلاب المسجلين',
  declined_rejected: 'مرفوض / مرفوض',
  review_applications: 'مراجعة الطلبات',
  academic_programs_enrollment: 'البرامج الأكاديمية وكثافة التسجيل',
  leading_programs: 'أهم برامج الدرجة مرتبة حسب حجم الطلاب',
  no_program_data: 'لا توجد بيانات توزيع البرامج متاحة.',
  enrolled_students_count: 'الطلاب المسجلين',
  offered_courses: 'المقررات المقدمة',
  active_cohort_progression: 'تقدم الدفعة النشطة',
  semester_breakdown: 'الطلاب مصنفون حسب تقدم الفصل الدراسي',
  no_semester_data: 'لا توجد بيانات تفصيلية للفصل الدراسي متاحة.',
  students_count: 'الطلاب',
  candidates_awaiting_review: 'المرشحين في انتظار المراجعة',
  view_all: 'عرض الكل',
  no_pending_admissions: 'لا توجد قبولات معلقة في الوقت الحالي.',
  review: 'مراجعة',
  recent_receipts: 'الإيصالات الأخيرة',
  incoming_payments: 'مدفوعات الكاشير والبنك الواردة',
  ledger: 'السجل',
  no_payment_transactions: 'لا توجد معاملات دفع مسجلة مؤخراً.',
  faculty_teaching: 'تدريس أعضاء هيئة التدريس',
  active_schedules: 'جداول المقررات والقاعات النشطة',
  assignments: 'المهام',
  no_teaching_assignments: 'لا توجد مهام تدريس مخصصة.',
  administrative_management: 'دليل الإدارة الإدارية',
  quick_navigation: 'التنقل السريع إلى وحدات الإدارة الأساسية والتكوينات',
  students_directory: 'دليل الطلاب',
  directory_profiles: 'الدليل والملفات الشخصية',
  admissions_screen: 'القبول',
  screen_admit: 'الفرز والقبول',
  lecturers_staff: 'المحاضرون',
  faculty_staff: 'أعضاء هيئة التدريس',
  courses_curriculum: 'المقررات',
  curriculum_syllabus: 'المنهج وتوصيف المقررات',
  finance_billing: 'المالية',
  billing_collections: 'الفوترة والتحصيل',
  hr_personnel: 'الموارد البشرية',
  personnel_payroll: 'الموظفين والرواتب',
  reports_analytics: 'التحليلات',
  analytics_insights: 'التحليلات والرؤى',
  settings_config: 'الإعدادات',
  system_config: 'تكوين النظام',
  teaching_allocation: 'التدريس',
  course_allocation: 'تخصيص المقررات',
  reports_institutional: 'التقارير',
  institutional_data: 'البيانات المؤسسية',
  users_roles: 'المستخدمون والأدوار',
  security_access: 'الأمان والوصول',

  // Students Page
  students_management: 'إدارة الطلاب',
  students_description: 'إدارة ومراقبة جميع سجلات الطلاب المسجلين، الأداء الأكاديمي، وحالة الرسوم.',
  import_students: 'استيراد الطلاب',
  create_student: 'إنشاء طالب',
  total_students: 'إجمالي الطلاب',
  active_enrolled: 'مسجلين نشطين',
  pending_enrollment: 'تسجيل معلق',
  suspended_status: 'موقوف',
  graduated_status: 'خريج',
  students_list: 'قائمة الطلاب',
  search_students: 'بحث بالاسم، البريد الإلكتروني، الرقم الجامعي، الهاتف...',
  status: 'الحالة',
  fee_status: 'حالة الرسوم',
  program: 'البرنامج',
  semester_label: 'الفصل الدراسي',
  gender: 'الجنس',
  all_statuses: 'جميع الحالات',
  enrolled_status: 'مسجل',
  pending_status: 'معلق',
  suspended_label: 'موقوف',
  graduated_label: 'خريج',
  withdrawn: 'منسحب',
  all_fees: 'جميع الرسوم',
  paid: 'مدفوع',
  unpaid: 'غير مدفوع',
  partial: 'جزئي',
  all_programs: 'جميع البرامج',
  all_semesters: 'جميع الفصول',
  all_genders: 'جميع الأجناس',
  male: 'ذكر',
  female: 'أنثى',
  delete_student_record: 'حذف سجل الطالب',
  delete_student_description: 'هل أنت متأكد من حذف هذا الطالب؟ سيتم إلغاء تنشيط حساب المستخدم الخاص به.',
  student_deleted_success: 'تم حذف الطالب {matric_no} بنجاح.',
  failed_delete_student: 'فشل حذف الطالب.',
  student_account_activated: 'تم تنشيط حساب الطالب.',
  student_account_suspended: 'تم إيقاف حساب الطالب.',
  failed_update_status: 'فشل تحديث حالة حساب الطالب.',
  breadcrumb_students: 'الطلاب',
};

export default ar;
