const ar = {
  // Admissions & Students
  admission: 'القبول',
  applicant: 'المتقدم',
  student: 'الطالب',
  student_id: 'الرقم الجامعي',
  enrollment: 'التسجيل / الالتحاق',
  transfer: 'التحويل',
  withdrawal: 'الانسحاب',
  graduate: 'الخريج',

  // Academic Structure
  faculty_college: 'الكلية',
  department: 'القسم',
  program_major: 'التخصص',
  course: 'المقرر',
  credit_hours: 'الساعات المعتمدة',
  semester: 'الفصل الدراسي',
  academic_year: 'العام الدراسي',
  prerequisite: 'المتطلب السابق',
  syllabus: 'توصيف المقرر',
  study_plan: 'الخطة الدراسية',

  // Registration & Timetable
  course_registration: 'تسجيل المقررات',
  add_drop: 'الحذف والإضافة',
  section: 'الشعبة',
  timetable: 'الجدول الدراسي',
  lecture_hall: 'قاعة المحاضرات',
  attendance: 'الحضور',
  absence: 'الغياب',
  academic_advisor: 'المرشد الأكاديمي',

  // Exams & Grades
  exam: 'الاختبار',
  midterm: 'الاختبار النصفي',
  final_exam: 'الاختبار النهائي',
  grade: 'الدرجة',
  gpa: 'المعدل التراكمي',
  semester_gpa: 'المعدل الفصلي',
  transcript: 'كشف الدرجات',
  academic_probation: 'الإنذار الأكاديمي',
  incomplete: 'غير مكتمل',
  result: 'النتيجة',

  // Faculty & HR
  instructor_lecturer: 'المحاضر',
  professor: 'الأستاذ',
  teaching_assistant: 'المعيد',
  employee: 'الموظف',
  payroll: 'الرواتب',
  leave: 'الإجازة',
  contract: 'العقد',
  job_title: 'المسمى الوظيفي',

  // Finance
  tuition_fees: 'الرسوم الدراسية',
  invoice: 'الفاتورة',
  payment: 'الدفع',
  scholarship: 'المنحة الدراسية',
  discount: 'الخصم',
  refund: 'الاسترداد',
  budget: 'الميزانية',
  receipt: 'الإيصال',

  // Library & Services
  library: 'المكتبة',
  borrowing: 'الاستعارة',
  housing_dormitory: 'السكن الجامعي',
  certificate: 'الشهادة',
  graduation_clearance: 'إخلاء الطرف',

  // System / General
  dashboard: 'لوحة التحكم',
  user: 'المستخدم',
  role: 'الدور',
  permission: 'الصلاحية',
  report: 'التقرير',
  notification: 'الإشعار',
  settings: 'الإعدادات',
  login: 'تسجيل الدخول',
  search: 'بحث',
  save: 'حفظ',
  cancel: 'إلغاء',
  delete: 'حذف',

  // Admin Dashboard
  admin_dashboard: 'لوحة إدارة الجامعة',
  system_active: 'النشط',
  overview_metrics: 'نظرة عامة على المؤشرات الرئيسية والنشاط الأخير في الجامعة.',
  register_student: 'تسجيل طالب',
  admissions_queue: 'قائمة القبول',
  analytics: 'التحليلات',
  total_enrollment: 'إجمالي التسجيل',
  actively_enrolled: 'مسجلين بشكل نشط',
  academic_faculty: 'الهيئة الأكاديمية',
  on_active_teaching: 'في التدريس النشط',
  total_programs: 'إجمالي البرامج',
  active_courses: 'المقررات النشطة',
  total_collected: 'إجمالي المحصّل',
  collection_rate: 'معدل التحصيل',
  outstanding_fees: 'الرسوم المستحقة',
  pending_clearance: 'معلق لإخلاء الطرف',
  pending_admissions: 'القبول المعلق',
  total_applied: 'إجمالي المتقدمين',
  active_teaching: 'التدريس النشط',
  total_sections: 'إجمالي الأقسام',
  graduated_alumni: 'الخريجين',
  issued_certs: 'الشهادات الصادرة',
  student_status_distribution: 'توزيع حالة الطلاب',
  total: 'الإجمالي',
  enrollment_lifecycle: 'تفصيل دورة حياة التسجيل عبر جميع الأقسام',
  enrolled: 'مسجل',
  pending: 'معلق',
  suspended: 'موقوف',
  graduated: 'خريج',
  open_student_directory: 'فتح دليل الطلاب',
  tuition_fees_health: 'صحة الرسوم الدراسية',
  collected: 'محصّل',
  invoiced_totals: 'إجمالي الفواتير مقابل مدفوعات الطلاب المحصّلة',
  collection_progress: 'تقدم التحصيل',
  total_invoiced: 'إجمالي الفواتير',
  cleared_payments: 'المدفوعات المحصّلة',
  outstanding_balance: 'الرصيد المستحق',
  view_detailed_ledger: 'عرض السجل التفصيلي',
  admissions_funnel: 'قمع القبول',
  candidates: 'المرشحين',
  applicant_flow: 'تدفق المتقدمين الجدد وتحويلهم إلى طلاب مسجلين',
  pending_review: 'قيد المراجعة',
  approved_offers: 'العروض المعتمدة',
  enrolled_students: 'الطلاب المسجلين',
  declined_rejected: 'مرفوض / مرفوض',
  review_applications: 'مراجعة الطلبات',
  academic_programs_enrollment: 'البرامج الأكاديمية وكثافة التسجيل',
  leading_programs: 'أهم برامج الدرجة مرتبة حسب حجم الطلاب',
  no_program_data: 'لا توجد بيانات توزيع البرامج متاحة.',
  active_cohort_progression: 'تقدم الدفعة النشطة',
  semester_breakdown: 'الطلاب مصنفون حسب تقدم الفصل الدراسي',
  no_semester_data: 'لا توجد بيانات تفصيلية للفصل الدراسي متاحة.',
  students_count: 'الطلاب',
  candidates_awaiting_review: 'المرشحين في انتظار المراجعة',
  view_all: 'عرض الكل',
  no_pending_admissions: 'لا توجد قبولات معلقة في الوقت الحالي.',
  review: 'مراجعة',
  recent_receipts: 'الإيصالات الأخيرة',
  incoming_payments: 'مدفوعات الكاشير والبنك الواردة',
  ledger: 'السجل',
  no_payment_transactions: 'لا توجد معاملات دفع مسجلة مؤخراً.',
  faculty_teaching: 'تدريس أعضاء هيئة التدريس',
  active_schedules: 'جداول المقررات والقاعات النشطة',
  assignments: 'المهام',
  no_teaching_assignments: 'لا توجد مهام تدريس مخصصة.',
  administrative_management: 'دليل الإدارة الإدارية',
  quick_navigation: 'التنقل السريع إلى وحدات الإدارة الأساسية والتكوينات',
  students_directory: 'دليل الطلاب',
  directory_profiles: 'الدليل والملفات الشخصية',
  admissions_screen: 'القبول',
  screen_admit: 'الفرز والقبول',
  lecturers_staff: 'المحاضرون',
  faculty_staff: 'أعضاء هيئة التدريس',
  courses_curriculum: 'المقررات',
  curriculum_syllabus: 'المنهج وتوصيف المقررات',
  finance_billing: 'المالية',
  billing_collections: 'الفوترة والتحصيل',
  hr_personnel: 'الموارد البشرية',
  personnel_payroll: 'الموظفين والرواتب',
  reports_analytics: 'التحليلات',
  analytics_insights: 'التحليلات والرؤى',
  settings_config: 'الإعدادات',
  system_config: 'تكوين النظام',
  teaching_allocation: 'التدريس',
  course_allocation: 'تخصيص المقررات',
  reports_institutional: 'التقارير',
  institutional_data: 'البيانات المؤسسية',
  users_roles: 'المستخدمون والأدوار',
  security_access: 'الأمان والوصول',

  // Students Page
  students_management: 'إدارة الطلاب',
  students_description: 'إدارة ومراقبة جميع سجلات الطلاب المسجلين، الأداء الأكاديمي، وحالة الرسوم.',
  import_students: 'استيراد الطلاب',
  create_student: 'إنشاء طالب',
  total_students: 'إجمالي الطلاب',
  active_enrolled: 'مسجلين نشطين',
  pending_enrollment: 'تسجيل معلق',
  suspended_status: 'موقوف',
  graduated_status: 'خريج',
  students_list: 'قائمة الطلاب',
  search_students: 'بحث بالاسم، البريد الإلكتروني، الرقم الجامعي، الهاتف...',
  status: 'الحالة',
  fee_status: 'حالة الرسوم',
  program: 'البرنامج',
  semester_label: 'الفصل الدراسي',
  gender: 'الجنس',
  all_statuses: 'جميع الحالات',
  enrolled_status: 'مسجل',
  pending_status: 'معلق',
  suspended_label: 'موقوف',
  graduated_label: 'خريج',
  withdrawn: 'منسحب',
  all_fees: 'جميع الرسوم',
  paid: 'مدفوع',
  unpaid: 'غير مدفوع',
  partial: 'جزئي',
  all_programs: 'جميع البرامج',
  all_semesters: 'جميع الفصول',
  all_genders: 'جميع الأجناس',
  male: 'ذكر',
  female: 'أنثى',
  delete_student_record: 'حذف سجل الطالب',
  delete_student_description: 'هل أنت متأكد من حذف هذا الطالب؟ سيتم إلغاء تنشيط حساب المستخدم الخاص به.',
  student_deleted_success: 'تم حذف الطالب {matric_no} بنجاح.',
  failed_delete_student: 'فشل حذف الطالب.',
  student_account_activated: 'تم تنشيط حساب الطالب.',
  student_account_suspended: 'تم إيقاف حساب الطالب.',
  failed_update_status: 'فشل تحديث حالة حساب الطالب.',
  breadcrumb_students: 'الطلاب',

  // Admissions Page
  admissions_management: 'إدارة القبول',
  admissions_description: 'مراجعة ومعالجة طلبات قبول الطلاب، اعتماد المرشحين، وتحويلهم إلى طلاب مسجلين.',
  applications_list: 'قائمة الطلبات',
  search_applications: 'بحث بالاسم، البريد الإلكتروني، رقم الطلب...',
  create_application: 'إنشاء طلب',
  application_no: 'رقم الطلب',
  applicant_name: 'اسم المتقدم',
  program_applied: 'البرنامج المقدم له',
  application_date: 'تاريخ الطلب',
  application_status: 'حالة الطلب',
  pending_application: 'معلق',
  approved_application: 'معتمد',
  rejected_application: 'مرفوض',
  admitted_application: 'مقبول',
  review_application: 'مراجعة الطلب',
  convert_to_student: 'تحويل إلى طالب',
  application_approved: 'تم اعتماد الطلب بنجاح.',
  application_rejected: 'تم رفض الطلب بنجاح.',
  under_review: 'قيد المراجعة',
  all_students: 'جميع الطلاب',
  total_applications: 'إجمالي الطلبات',
  enrolled_admissions: 'الطلاب المسجلين',
  delete_application: 'حذف الطلب',
  delete_application_confirm: 'هل أنت متأكد من حذف هذا الطلب؟',
  breadcrumb_admissions: 'القبول',

  // Lecturers Page
  lecturers_management: 'إدارة المحاضرين',
  lecturers_description: 'إدارة أعضاء هيئة التدريس، المهام التدريسية، وتتبع الأداء الأكاديمي.',
  lecturers_list: 'قائمة المحاضرين',
  lecturers_directory: 'دليل المحاضرين',
  search_lecturers: 'بحث بالاسم، البريد الإلكتروني، القسم...',
  create_lecturer: 'إنشاء محاضر',
  lecturer_name: 'اسم المحاضر',
  lecturer_status: 'الحالة',
  active_lecturer: 'نشط',
  inactive_lecturer: 'غير نشط',
  courses_taught: 'المقررات المدرسة',
  on_leave: 'في إجازة',
  sabbatical: 'إجازة سباستيكال',
  terminated: 'منتهي العقد',
  full_time: 'دوام كامل',
  part_time: 'دوام جزئي',
  adjunct: 'محاضر زائر',
  visiting: 'زائر',
  total_faculty: 'إجمالي الهيئة',
  registered_academic_staff: 'أعضاء هيئة التدريس المسجلين',
  currently_lecturing: 'يقدم محاضرات حالياً',
  sabbatical_leave: 'إجازة سباستيكال',
  permanent_faculty: 'هيئة دائمة',
  part_time_adjunct: 'دوام جزئي / زائر',
  visiting_adjunct_staff: 'أعضاء هيئة زائرين',
  delete_lecturer: 'حذف سجل المحاضر',
  delete_lecturer_confirm: 'هل أنت متأكد من حذف هذا المحاضر؟ سيتم إلغاء تنشيط حساب المستخدم الخاص به.',
  lecturer_deleted: 'تم حذف المحاضر {name} بنجاح.',
  failed_delete_lecturer: 'فشل حذف سجل المحاضر.',
  lecturer_status_updated: 'تم تحديث حالة المحاضر بنجاح.',
  failed_update_lecturer_status: 'فشل تحديث حالة المحاضر.',
  reset_lecturer_password: 'إعادة تعيين كلمة مرور المحاضر',
  reset_password_description: 'تعيين كلمة مرور آمنة جديدة لحساب عضو هيئة التدريس هذا.',
  breadcrumb_lecturers: 'المحاضرون',

  // Assignments Page
  assignments_management: 'المهام التدريسية',
  assignments_description: 'إدارة مهام المقررات، جداول التدريس، وتخصيص القاعات.',
  assignments_list: 'قائمة المهام',
  search_assignments: 'بحث برمز المقرر، اسم المحاضر...',
  create_assignment: 'إنشاء مهمة',
  course_code: 'رمز المقرر',
  course_name: 'اسم المقرر',
  assigned_lecturer: 'المحاضر المعين',
  schedule: 'الجدول',
  room: 'القاعة',
  assignment_status: 'الحالة',
  active_assignment: 'نشط',
  completed_assignment: 'مكتمل',
  all_years: 'جميع السنوات',
  all_lecturers: 'جميع المحاضرين',
  all_courses: 'جميع المقررات',
  assigned: 'معين',
  cancelled: 'ملغي',
  total_assignments: 'إجمالي المهام',
  delete_assignment: 'حذف المهمة',
  delete_assignment_confirm: 'هل أنت متأكد من حذف هذه المهمة؟',
  assignment_deleted: 'تم حذف المهمة بنجاح.',
  failed_delete_assignment: 'فشل حذف المهمة.',
  semester_1: 'الفصل الأول',
  semester_2: 'الفصل الثاني',
  semester_3: 'الفصل الثالث',
  semester_4: 'الفصل الرابع',
  semester_5: 'الفصل الخامس',
  semester_6: 'الفصل السادس',
  breadcrumb_assignments: 'المهام',

  // Programs Page
  programs_management: 'البرامج الأكاديمية',
  programs_description: 'إدارة برامج الدرجة، هيكل المنهج، ومتطلبات البرنامج.',
  programs_list: 'قائمة البرامج',
  search_programs: 'بحث باسم البرنامج، الرمز...',
  create_program: 'إنشاء برنامج',
  program_name: 'اسم البرنامج',
  program_code: 'رمز البرنامج',
  program_level: 'المستوى',
  program_duration: 'المدة (سنوات)',
  credit_requirements: 'متطلبات الساعات المعتمدة',
  code: 'الرمز',
  program_name_label: 'اسم البرنامج',
  degree_level: 'مستوى الدرجة',
  duration_semesters: 'المدة (فصول)',
  total_credits: 'إجمالي الساعات المعتمدة',
  faculty_label: 'الكلية',
  program_status: 'الحالة',
  all_faculties: 'جميع الكليات',
  all_degree_levels: 'جميع مستويات الدرجة',
  bachelor: 'بكالوريوس',
  master: 'ماجستير',
  phd: 'دكتوراه',
  diploma: 'دبلوم',
  program_active: 'نشط',
  program_inactive: 'غير نشط',
  delete_program: 'حذف البرنامج',
  delete_program_confirm: 'هل أنت متأكد من حذف هذا البرنامج؟',
  program_deleted: 'تم حذف البرنامج {name}.',
  failed_delete_program: 'فشل حذف البرنامج الأكاديمي.',
  total_programs_stats: 'إجمالي البرامج',
  active_programs_stats: 'البرامج النشطة',
  total_students_stats: 'إجمالي الطلاب',
  total_courses_stats: 'إجمالي المقررات',
  faculties_count: 'عدد الكليات',
  archived: 'مؤرشف',
  actions: 'الإجراءات',
  view: 'عرض',
  breadcrumb_programs: 'البرامج',

  // Courses Page
  courses_management: 'إدارة المقررات',
  courses_description: 'إدارة كتالوج المقررات، المتطلبات السابقة، ومواد المقررات.',
  courses_list: 'قائمة المقررات',
  search_courses: 'بحث برمز المقرر، الاسم...',
  create_course: 'إنشاء مقرر',
  course_title: 'عنوان المقرر',
  course_credits: 'الساعات المعتمدة',
  course_prerequisites: 'المتطلبات السابقة',
  breadcrumb_courses: 'المقررات',

  // Semesters Page
  semesters_management: 'الفصول الدراسية',
  semesters_description: 'إدارة التقويم الأكاديمي، جداول الفصول، وفترات التسجيل.',
  semesters_list: 'قائمة الفصول',
  create_semester: 'إنشاء فصل دراسي',
  semester_name: 'اسم الفصل',
  start_date: 'تاريخ البدء',
  end_date: 'تاريخ الانتهاء',
  registration_period: 'فترة التسجيل',
  breadcrumb_semesters: 'الفصول',

  // Enrollments Page
  enrollments_management: 'تسجيل المقررات',
  enrollments_description: 'إدارة تسجيل الطلاب في المقررات، طلبات الحذف والإضافة، وحالة التسجيل.',
  enrollments_list: 'قائمة التسجيلات',
  search_enrollments: 'بحث بالطالب، المقرر...',
  create_enrollment: 'إنشاء تسجيل',
  enrollment_student: 'الطالب',
  enrollment_course: 'المقرر',
  enrollment_semester: 'الفصل الدراسي',
  enrollment_status: 'حالة التسجيل',
  breadcrumb_enrollments: 'التسجيل',

  // Transcripts Page
  transcripts_management: 'السجلات الأكاديمية',
  transcripts_description: 'عرض وإدارة السجلات الأكاديمية للطلاب، الدرجات، وتوليد كشوف الدرجات.',
  transcripts_list: 'قائمة السجلات',
  search_transcripts: 'بحث باسم الطالب، الرقم الجامعي...',
  generate_transcript: 'توليد كشف درجات',
  student_record: 'سجل الطالب',
  academic_performance: 'الأداء الأكاديمي',
  transcript_generated: 'تم توليد كشف الدرجات بنجاح.',
  breadcrumb_transcripts: 'السجلات',

  // Finance Pages
  finance_management: 'الإدارة المالية',
  finance_description: 'إدارة الرسوم الدراسية، الفواتير، المدفوعات، والتقارير المالية.',
  finance_list: 'قائمة المالية',
  search_finance: 'بحث برقم الفاتورة، الطالب...',
  create_invoice: 'إنشاء فاتورة',
  invoice_no: 'رقم الفاتورة',
  invoice_amount: 'المبلغ',
  invoice_due_date: 'تاريخ الاستحقاق',
  invoice_status: 'الحالة',
  payment_list: 'قائمة المدفوعات',
  search_payments: 'بحث برقم المعاملة، الطالب...',
  record_payment: 'تسجيل دفع',
  transaction_no: 'رقم المعاملة',
  payment_amount: 'المبلغ',
  payment_method: 'طريقة الدفع',
  payment_date: 'تاريخ الدفع',
  fees_management: 'إدارة الرسوم',
  fees_description: 'إدارة هيكل الرسوم، خطط الدفع، وإعفاءات الرسوم.',
  breadcrumb_finance: 'المالية',
  breadcrumb_fees: 'الرسوم',
  breadcrumb_payments: 'المدفوعات',
  breadcrumb_invoices: 'الفواتير',

  // Expenses Page
  expenses_management: 'إدارة المصروفات',
  expenses_description: 'تتبع وإدارة مصروفات الجامعة، الميزانيات، وتخصيص التكاليف.',
  expenses_list: 'قائمة المصروفات',
  search_expenses: 'بحث بنوع المصروف، التاريخ...',
  create_expense: 'إنشاء مصروف',
  expense_type: 'نوع المصروف',
  expense_category: 'الفئة',
  expense_amount: 'المبلغ',
  expense_date: 'التاريخ',
  expense_description: 'الوصف',
  breadcrumb_expenses: 'المصروفات',

  // Chart of Accounts Page
  chart_of_accounts: 'دليل الحسابات',
  chart_description: 'إدارة الحسابات المالية، رموز الحسابات، وهيكل المحاسبة.',
  accounts_list: 'قائمة الحسابات',
  search_accounts: 'بحث برمز الحساب، الاسم...',
  create_account: 'إنشاء حساب',
  account_code: 'رمز الحساب',
  account_name: 'اسم الحساب',
  account_type: 'نوع الحساب',
  parent_account: 'الحساب الرئيسي',
  breadcrumb_chart_of_accounts: 'دليل الحسابات',

  // Reports Page
  reports_management: 'التقارير',
  reports_description: 'عرض وتوليد تقارير متنوعة للتحليل الأكاديمي والمالي والإداري.',
  reports_list: 'قائمة التقارير',
  generate_report: 'توليد تقرير',
  report_type: 'نوع التقرير',
  date_range: 'نطاق التاريخ',
  export_report: 'تصدير التقرير',
  breadcrumb_reports: 'التقارير',

  // Settings - System
  system_settings: 'إعدادات النظام',
  system_settings_description: 'تكوين إعدادات النظام، التفضيلات، وتكوين التطبيق.',
  application_name: 'اسم التطبيق',
  timezone: 'المنطقة الزمنية',
  date_format: 'تنسيق التاريخ',
  time_format: 'تنسيق الوقت',
  language: 'اللغة',
  maintenance_mode: 'وضع الصيانة',
  save_settings: 'حفظ الإعدادات',
  breadcrumb_system_settings: 'إعدادات النظام',

  // Settings - Roles
  roles_management: 'الأدوار والصلاحيات',
  roles_description: 'إدارة أدوار المستخدمين، الصلاحيات، والتحكم في الوصول.',
  roles_list: 'قائمة الأدوار',
  create_role: 'إنشاء دور',
  role_name: 'اسم الدور',
  permissions: 'الصلاحيات',
  assign_permissions: 'تعيين الصلاحيات',
  delete_role: 'حذف الدور',
  delete_role_confirm: 'هل أنت متأكد من حذف هذا الدور؟',
  breadcrumb_roles: 'الأدوار',

  // Settings - Audit Log
  audit_log: 'سجل التدقيق',
  audit_log_description: 'عرض سجلات نشاط النظام، إجراءات المستخدمين، والأحداث الأمنية.',
  audit_logs_list: 'سجلات التدقيق',
  filter_logs: 'تصفية السجلات',
  user_action: 'إجراء المستخدم',
  event_type: 'نوع الحدث',
  ip_address: 'عنوان IP',
  timestamp: 'الطابع الزمني',
  breadcrumb_audit_log: 'سجل التدقيق',

  // Settings - Users
  users_management: 'إدارة المستخدمين',
  users_description: 'إدارة مستخدمي النظام، الحسابات، والوصول للمستخدمين.',
  users_list: 'قائمة المستخدمين',
  create_user: 'إنشاء مستخدم',
  user_name: 'اسم المستخدم',
  user_email: 'البريد الإلكتروني',
  user_role: 'دور المستخدم',
  user_status: 'حالة المستخدم',
  deactivate_user: 'إلغاء تنشيط المستخدم',
  activate_user: 'تنشيط المستخدم',
  reset_password: 'إعادة تعيين كلمة المرور',
  delete_user: 'حذف المستخدم',
  delete_user_confirm: 'هل أنت متأكد من حذف هذا المستخدم؟',
  breadcrumb_users: 'المستخدمون',

  // Reports Page Metrics
  program_distribution: 'توزيع البرامج',
  admission_pipeline: 'خط القبول',
  lecturer_assignments_reports: 'تعيينات المحاضرين',
  cohort_progression: 'تقدم الدفعات حسب الفصل',
  recent_payments_reports: 'المدفوعات الأخيرة',
  top_performers: 'أفضل الأداء الأكاديمي',
  program_leadership: 'قيادة البرنامج',
  active_cohort_progression: 'تقدم الدفعة النشطة',
  student_academic_progression: 'التقدم الأكاديمي للطلاب',
  student_academic_progression_description: 'تتبع احتفاظ الطلاب وتقدمهم عبر الفصول.',
  no_cohort_data: 'لا توجد بيانات تقدم دفعات متاحة.',
  total_certificates_issued: 'إجمالي الشهادات المصدرة',

  // System Settings Page
  system_configuration_saved: 'تم حفظ تكوين النظام بنجاح.',
  total_accounts: 'إجمالي الحسابات',
  enrolled_students_system: 'الطلاب المسجلون',
  total_programs_system: 'إجمالي البرامج',
  total_courses_system: 'إجمالي المقررات',
  total_lecturers_system: 'إجمالي المحاضرين',
  active_assignments_system: 'التعيينات النشطة',
  php_version: 'إصدار PHP',
  laravel_version: 'إصدار Laravel',
  server_software: 'برنامج الخادم',
  database_driver: 'محرك قاعدة البيانات',
  database_name: 'اسم قاعدة البيانات',
  cache_driver: 'محرك التخزين المؤقت',
  queue_driver: 'محرف الطابور',
  timezone_system: 'المنطقة الزمنية',
  environment: 'البيئة',
  debug_mode: 'وضع التصحيح',
  system_configuration_diagnostics: 'تكوين النظام وتشخيص الخادم',
  system_institutional_configurations: 'تكوينات النظام والمؤسسة',
  system_config_description: 'إدارة بيانات المؤسسة، أقفال تسجيل البوابة، تواريخ الجلسة الأكاديمية، وصحة بيئة الخادم.',
  saving_changes: 'جاري الحفظ...',
  save_changes: 'حفظ التغييرات',
  institution_name: 'اسم المؤسسة',
  institution_motto: 'شعار المؤسسة',
  contact_email: 'البريد الإلكتروني للاتصال',
  contact_phone: 'رقم الهاتف',
  campus_address: 'عنوان الحرم الجامعي',
  academic_year: 'السنة الأكاديمية',
  current_term: 'الفصل الحالي',
  student_registration_enabled: 'تسجيل الطالب مفعل',
  course_enrollment_open: 'تسجيل المقرر مفتوح',
  maintenance_mode_system: 'وضع الصيانة',
  late_fee_percentage: 'نسبة رسوم التأخير',

  // Courses Page
  course_deleted: 'تم حذف المقرر {code} - {name}.',
  failed_delete_course: 'فشل حذف المقرر.',
  general_program: 'البرنامج العام',
  lecturer_assignments_label: 'تعيينات المحاضرين',
  all_semesters_filter: 'جميع الفصول',
  all_levels_filter: 'جميع المستويات',
  all_programs_filter: 'جميع البرامج',
  semester_prefix: 'فصل',
  delete_course: 'حذف المقرر',
  delete_course_confirm: 'هل أنت متأكد من حذف هذا المقرر؟',
  active_courses_stats: 'المقررات النشطة',
  total_assignments_stats: 'إجمالي التعيينات',
  total_credits_stats: 'إجمالي الساعات المعتمدة',

  // Semesters Page
  semester_curricula_cohorts: 'مناهج الفصول والدفعات',
  semester_overview_cohort: 'نظرة عامة على الفصول وتوزيع الدفعات',
  semester_description: 'عرض توزيع المناهج حسب الفصل، أحجام الدفعات، وتخصيص المقررات عبر جميع البرامج الأكاديمية.',
  total_semesters_stats: 'إجمالي الفصول',
  active_cohorts_stats: 'الدفعات النشطة',
  total_courses_offered_stats: 'إجمالي المقررات المقدمة',
  total_enrolled_students_stats: 'إجمالي الطلاب المسجلين',
  filter_by_program: 'تصفية حسب البرنامج',
  all_programs_semesters: 'جميع البرامج',
  semester_label_page: 'الفصل',
  level_label: 'المستوى',
  courses_count_label: 'المقررات',
  students_count_label: 'الطلاب',
  total_credits_label: 'إجمالي الساعات المعتمدة',
  view_courses: 'عرض المقررات',
  active_status: 'نشط',
  program_semesters: 'فصول البرنامج',
  workload: 'عبء العمل',
  curriculum_courses: 'مقررات المنهج',
  no_courses_configured: 'لم يتم تكوين مقررات بعد.',

  // Enrollments Page
  total_enrolled_stats: 'إجمالي المسجلين',
  active_students_enrollments: 'الطلاب النشطون',
  pending_enrollments_stats: 'التسجيلات المعلقة',
  graduated_students_enrollments: 'الطلاب الخريجون',
  suspended_students_enrollments: 'الطلاب المعلقون',
  matric_number: 'الرقم الجامعي',
  enrollment_status_page: 'حالة التسجيل',
  current_semester_enrollment: 'الفصل الحالي',
  fee_status_enrollment: 'حالة الرسوم',
  enrollment_date_label: 'تاريخ التسجيل',
  gpa_label_enrollment: 'المعدل التراكمي',
  enrollment_active: 'نشط',
  enrollment_pending: 'معلق',
  enrollment_graduated: 'خريج',
  enrollment_suspended: 'معلق',
  enrolled_status_enrollment: 'مسجل',
  pending_fee_status: 'معلق',
  paid_fee_status: 'مدفوع',
  partial_fee_status: 'جزئي',
  view_enrollment: 'عرض التسجيل',
  unassigned: 'غير معين',
  term: 'الفصل',
  enroll_student: 'تسجيل طالب',
  enrollment_roster: 'قائمة التسجيل',

  // Transcripts Page
  total_students_transcripts: 'إجمالي الطلاب',
  avg_institution_gpa: 'متوسط المعدل التراكمي للمؤسسة',
  total_grades_recorded: 'إجمالي الدرجات المسجلة',
  certificates_issued: 'الشهادات المصدرة',
  grades_count_label: 'الدرجات',
  certificates_count_label: 'الشهادات',
  transcript_student_name: 'اسم الطالب',
  transcript_program: 'البرنامج',
  transcript_term: 'الفصل',
  transcript_gpa: 'المعدل التراكمي',
  view_transcript: 'عرض السجل الأكاديمي',
  generate_transcript_button: 'توليد كشف درجات',
  cumulative_gpa: 'المعدل التراكمي',
  issued: 'مصدرة',

  // Finance Overview Page
  financial_solvency_revenue: 'الملاءة المالية ونظرة عامة على الإيرادات',
  finance_bursar_center: 'مركز التحكم المالي ومكتب الخزينة',
  finance_description: 'تقييم رسوم الدراسية في الوقت الفعلي، تحصيل الرسوم، التحقق من دفعات الطلاب، وتدفق السيولة النقدية.',
  total_invoiced_finance: 'إجمالي الفواتير',
  total_collected_finance: 'إجمالي المحصل',
  total_outstanding_finance: 'إجمالي المستحق',
  pending_payments_finance: 'المدفوعات المعلقة',
  overdue_invoices_finance: 'الفواتير المتأخرة',
  recent_transactions: 'المعاملات الأخيرة',
  recent_invoices_finance: 'الفواتير الأخيرة',
  revenue_by_payment_method: 'الإيرادات حسب طريقة الدفع',
  invoices_by_type: 'الفواتير حسب النوع',
  transaction_no_label: 'رقم المعاملة',
  payment_date_label: 'تاريخ الدفع',
  invoice_no_label: 'رقم الفاتورة',
  invoice_title: 'العنوان',
  invoice_type: 'النوع',
  paid_amount: 'المبلغ المدفوع',
  due_date_label: 'تاريخ الاستحقاق',
  view_all_payments: 'عرض جميع المدفوعات',
  view_all_invoices: 'عرض جميع الفواتير',
  manage_fees: 'إدارة الرسوم',
  chart_of_accounts_label: 'دليل الحسابات',
  no_payment_transactions: 'لم يتم تسجيل معاملات دفع بعد.',
  no_invoices_recorded: 'لم يتم تسجيل فواتير بعد.',
  recent_invoices_desc: 'أحدث فواتير الرسوم الدراسية والرسوم المصدرة للطلاب.',

  // Fees Page
  fee_schedules: 'جداول الرسوم',
  fee_schedules_description: 'إدارة هياكل رسوم الطلاب، خطط الدفع، وتقييمات الرسوم.',
  total_students_fees: 'إجمالي الطلاب',
  fully_paid_students: 'مدفوع بالكامل',
  partial_students: 'جزئي',
  unpaid_students: 'غير مدفوع',
  total_receivables: 'إجمالي المستحقات',
  matric_no_fees: 'الرقم الجامعي',
  total_billed: 'إجمالي المفوتر',
  total_paid_fees: 'إجمالي المدفوع',
  balance: 'الرصيد',
  fee_status_filter: 'حالة الرسوم',
  all_fee_statuses: 'جميع حالات الرسوم',
  fully_paid_status: 'مدفوع بالكامل',
  partial_status: 'جزئي',
  unpaid_status: 'غير مدفوع',
  program_filter_fees: 'البرنامج',
  all_programs_fees: 'جميع البرامج',
  view_student_profile: 'عرض الملف الشخصي',
  institutional_tuition_schedule: 'جدول الرسوم الدراسي المؤسسي (السنة الأكاديمية القياسية 2026/2027)',
  fees_list_label: 'دليل رسوم الطلاب',
  search_fees: 'بحث بالرقم الجامعي، اسم الطالب...',
  approved_fee_schedule: 'جدول الرسوم المعتمد حسب برنامج الدرجة بالكلية.',
  undergraduate_tuition: 'رسوم الدراسة الجامعية',
  postgraduate_tuition: 'رسوم الدراسات العليا',
  one_time_institutional_fees: 'الرسوم المؤسسية لمرة واحدة',
  includes_registration: 'يشمل تسجيل المقرر، الوصول إلى المختبر، مكتبة الحرم، ورسوم الامتحانات.',
  includes_thesis: 'يشمل إشراف الأطروح المتقدمة، مستود المجلات، والمرافق المخبرية.',
  admission_matriculation: 'القبول والتسجيل',
  graduation_transcript: 'التخرج والسجل الأكاديمي',
  bachelor: 'بكالوريوس',
  master: 'ماجستير',
  phd: 'دكتوراه',

  // Payments Page
  payments_roster: 'سجل المدفوعات',
  payments_description: 'تتبع وإدارة جميع معاملات دفع الطلاب، طرق الدفع، والمطابقة.',
  payments_list: 'قائمة المدفوعات',
  search_payments: 'بحث برقم المعاملة، اسم الطالب...',
  transaction_no_payments: 'رقم المعاملة',
  payment_amount_payments: 'المبلغ',
  payment_method_payments: 'طريقة الدفع',
  payment_date_payments: 'تاريخ الدفع',
  student_name_payments: 'اسم الطالب',
  program_payments: 'البرنامج',
  status_payments: 'الحالة',
  all_statuses_payments: 'جميع الحالات',
  completed_payment: 'مكتمل',
  pending_payment: 'معلق',
  failed_payment: 'فشل',
  refunded_payment: 'مسترد',
  record_payment: 'تسجيل دفع',
  payment_method_filter: 'طريقة الدفع',
  all_payment_methods: 'جميع الطرق',
  total_collected: 'إجمالي المحصل',
  pending_review: 'قيد المراجعة',
  todays_collections: 'تحصيلات اليوم',
  total_transactions: 'إجمالي المعاملات',
  approve: 'موافقة',
  reject: 'رفض',
  enter_payment_details: 'أدخل تفاصيل معاملة الدفع المستلمة من الطالب.',
  select_student: 'اختر الطالب',
  receipt_reference_note: 'إيصال / ملاحظة مرجعية',
  saving: 'جاري الحفظ...',
  no_due_date: 'لا يوجد تاريخ استحقاق',
  overdue: 'متأخر',
  paid_invoice: 'مدفوع',
  partial_paid_invoice: 'جزئي',
  items: 'العناصر',
  view: 'عرض',
  total_invoiced: 'إجمالي الفواتير',
  total_paid: 'إجمالي المدفوع',
  outstanding_due: 'المستحقات المتأخرة',
  issue_invoice: 'إصدار فاتورة',
  total_invoices: 'إجمالي الفواتير',
  overdue_invoices: 'الفواتير المتأخرة',
  bills: 'فواتير',
  issue_student_invoice: 'إصدار فاتورة طالب',
  create_invoice_description: 'إنشاء فاتورة رسمية مخصصة لسجل رسوم الطالب.',
  invoice_title: 'عنوان الفاتورة',
  fee_category: 'فئة الرسوم',
  line_items: 'بنود الفاتورة',
  add_item: 'إضافة عنصر',
  add_line_items_description: 'أضف بنود لتفصيل رسوم الفاتورة.',
  computed_amount: 'المبلغ المحسوب',
  delete_invoice: 'حذف الفاتورة',
  delete_invoice_description: 'هل أنت متأكد من أنك تريد حذف هذه الفاتورة؟ لا يمكن حذف الفواتير التي تم تحصيل المدفوعات منها.',

  // Invoices Page
  invoices_list_page: 'الفواتير',
  invoices_description: 'إدارة فواتير الرسوم الدراسية للطلاب، تقييمات الرسوم، وسجلات الفوترة.',
  invoices_list_label: 'قائمة الفواتير',
  search_invoices: 'بحث برقم الفاتورة، اسم الطالب...',
  invoice_no_invoices: 'رقم الفاتورة',
  invoice_title_invoices: 'العنوان',
  invoice_type_invoices: 'النوع',
  invoice_amount_invoices: 'المبلغ',
  due_date_invoices: 'تاريخ الاستحقاق',
  paid_amount_invoices: 'المبلغ المدفوع',
  balance_invoices: 'الرصيد',
  status_invoices: 'الحالة',
  all_statuses_invoices: 'جميع الحالات',
  draft_invoice: 'مسودة',
  sent_invoice: 'مرسلة',
  partial_paid_invoice: 'مدفوع جزئياً',
  paid_invoice: 'مدفوع',
  overdue_invoice: 'متأخرة',
  cancelled_invoice: 'ملغاة',
  create_invoice: 'إنشاء فاتورة',
  invoice_type_filter: 'نوع الفاتورة',
  all_invoice_types: 'جميع الأنواع',

  // Expenses Page
  expenses_management_page: 'إدارة المصروفات',
  expenses_description_page: 'تتبع وإدارة مصروفات الجامعة، الميزانيات، وتخصيص التكاليف.',
  expenses_list_page: 'قائمة المصروفات',
  search_expenses_page: 'بحث بنوع المصروف، التاريخ...',
  create_expense_page: 'إنشاء مصروف',
  expense_type_page: 'نوع المصروف',
  expense_category_page: 'الفئة',
  expense_amount_page: 'المبلغ',
  expense_date_page: 'التاريخ',
  expense_description_page: 'الوصف',
  all_expense_types: 'جميع الأنواع',
  all_categories: 'جميع الفئات',

  // Chart of Accounts Page
  chart_of_accounts_page: 'دليل الحسابات',
  chart_description_page: 'إدارة الحسابات المالية، رموز الحسابات، وهيكل المحاسبة.',
  accounts_list_page: 'قائمة الحسابات',
  search_accounts_page: 'بحث برمز الحساب، الاسم...',
  create_account_page: 'إنشاء حساب',
  account_code_page: 'رمز الحساب',
  account_name_page: 'اسم الحساب',
  account_type_page: 'نوع الحساب',
  parent_account_page: 'الحساب الرئيسي',
  all_account_types: 'جميع الأنواع',
  asset: 'أصل',
  liability: 'التزام',
  equity: 'حقوق الملكية',
  revenue: 'إيراد',
  expense: 'مصروف',
};

export default ar;
