const ar = {
  // Admissions & Students
  admission: 'القبول',
  applicant: 'المتقدم',
  student: 'الطالب',
  student_id: 'الرقم الجامعي',
  enrollment: 'التسجيل / الالتحاق',
  transfer: 'التحويل',
  withdrawal: 'الانسحاب',
  graduate: 'الخريج',

  // Academic Structure
  faculty_college: 'الكلية',
  department: 'القسم',
  program_major: 'التخصص',
  course: 'المقرر',
  credit_hours: 'الساعات المعتمدة',
  semester: 'الفصل الدراسي',
  academic_year: 'العام الدراسي',
  prerequisite: 'المتطلب السابق',
  syllabus: 'توصيف المقرر',
  study_plan: 'الخطة الدراسية',

  // Registration & Timetable
  course_registration: 'تسجيل المقررات',
  add_drop: 'الحذف والإضافة',
  section: 'الشعبة',
  timetable: 'الجدول الدراسي',
  lecture_hall: 'قاعة المحاضرات',
  attendance: 'الحضور',
  absence: 'الغياب',
  academic_advisor: 'المرشد الأكاديمي',

  // Exams & Grades
  exam: 'الاختبار',
  midterm: 'الاختبار النصفي',
  final_exam: 'الاختبار النهائي',
  grade: 'الدرجة',
  gpa: 'المعدل التراكمي',
  semester_gpa: 'المعدل الفصلي',
  transcript: 'كشف الدرجات',
  academic_probation: 'الإنذار الأكاديمي',
  incomplete: 'غير مكتمل',
  result: 'النتيجة',

  // Faculty & HR
  instructor_lecturer: 'المحاضر',
  professor: 'الأستاذ',
  teaching_assistant: 'المعيد',
  employee: 'الموظف',
  payroll: 'الرواتب',
  leave: 'الإجازة',
  contract: 'العقد',
  job_title: 'المسمى الوظيفي',

  // Finance
  tuition_fees: 'الرسوم الدراسية',
  invoice: 'الفاتورة',
  payment: 'الدفع',
  scholarship: 'المنحة الدراسية',
  discount: 'الخصم',
  refund: 'الاسترداد',
  budget: 'الميزانية',
  receipt: 'الإيصال',

  // Library & Services
  library: 'المكتبة',
  borrowing: 'الاستعارة',
  housing_dormitory: 'السكن الجامعي',
  certificate: 'الشهادة',
  graduation_clearance: 'إخلاء الطرف',

  // System / General
  dashboard: 'لوحة التحكم',
  user: 'المستخدم',
  role: 'الدور',
  permission: 'الصلاحية',
  report: 'التقرير',
  notification: 'الإشعار',
  settings: 'الإعدادات',
  login: 'تسجيل الدخول',
  search: 'بحث',
  save: 'حفظ',
  cancel: 'إلغاء',
  delete: 'حذف',

  // Admin Dashboard
  admin_dashboard: 'لوحة إدارة الجامعة',
  system_active: 'النشط',
  overview_metrics: 'نظرة عامة على المؤشرات الرئيسية والنشاط الأخير في الجامعة.',
  register_student: 'تسجيل طالب',
  admissions_queue: 'قائمة القبول',
  analytics: 'التحليلات',
  total_enrollment: 'إجمالي التسجيل',
  actively_enrolled: 'مسجلين بشكل نشط',
  academic_faculty: 'الهيئة الأكاديمية',
  on_active_teaching: 'في التدريس النشط',
  total_programs: 'إجمالي البرامج',
  active_courses: 'المقررات النشطة',
  total_collected: 'إجمالي المحصّل',
  collection_rate: 'معدل التحصيل',
  outstanding_fees: 'الرسوم المستحقة',
  pending_clearance: 'معلق لإخلاء الطرف',
  pending_admissions: 'القبول المعلق',
  total_applied: 'إجمالي المتقدمين',
  active_teaching: 'التدريس النشط',
  total_sections: 'إجمالي الأقسام',
  graduated_alumni: 'الخريجين',
  issued_certs: 'الشهادات الصادرة',
  student_status_distribution: 'توزيع حالة الطلاب',
  total: 'الإجمالي',
  enrollment_lifecycle: 'تفصيل دورة حياة التسجيل عبر جميع الأقسام',
  enrolled: 'مسجل',
  pending: 'معلق',
  suspended: 'موقوف',
  graduated: 'خريج',
  open_student_directory: 'فتح دليل الطلاب',
  tuition_fees_health: 'صحة الرسوم الدراسية',
  collected: 'محصّل',
  invoiced_totals: 'إجمالي الفواتير مقابل مدفوعات الطلاب المحصّلة',
  collection_progress: 'تقدم التحصيل',
  total_invoiced: 'إجمالي الفواتير',
  cleared_payments: 'المدفوعات المحصّلة',
  outstanding_balance: 'الرصيد المستحق',
  view_detailed_ledger: 'عرض السجل التفصيلي',
  admissions_funnel: 'قمع القبول',
  candidates: 'المرشحين',
  applicant_flow: 'تدفق المتقدمين الجدد وتحويلهم إلى طلاب مسجلين',
  pending_review: 'قيد المراجعة',
  approved_offers: 'العروض المعتمدة',
  enrolled_students: 'الطلاب المسجلين',
  declined_rejected: 'مرفوض / مرفوض',
  review_applications: 'مراجعة الطلبات',
  academic_programs_enrollment: 'البرامج الأكاديمية وكثافة التسجيل',
  leading_programs: 'أهم برامج الدرجة مرتبة حسب حجم الطلاب',
  no_program_data: 'لا توجد بيانات توزيع البرامج متاحة.',
  active_cohort_progression: 'تقدم الدفعة النشطة',
  semester_breakdown: 'الطلاب مصنفون حسب تقدم الفصل الدراسي',
  no_semester_data: 'لا توجد بيانات تفصيلية للفصل الدراسي متاحة.',
  students_count: 'الطلاب',
  candidates_awaiting_review: 'المرشحين في انتظار المراجعة',
  view_all: 'عرض الكل',
  no_pending_admissions: 'لا توجد قبولات معلقة في الوقت الحالي.',
  review: 'مراجعة',
  recent_receipts: 'الإيصالات الأخيرة',
  incoming_payments: 'مدفوعات الكاشير والبنك الواردة',
  ledger: 'السجل',
  no_payment_transactions: 'لا توجد معاملات دفع مسجلة مؤخراً.',
  faculty_teaching: 'تدريس أعضاء هيئة التدريس',
  active_schedules: 'جداول المقررات والقاعات النشطة',
  assignments: 'المهام',
  no_teaching_assignments: 'لا توجد مهام تدريس مخصصة.',
  administrative_management: 'دليل الإدارة الإدارية',
  quick_navigation: 'التنقل السريع إلى وحدات الإدارة الأساسية والتكوينات',
  students_directory: 'دليل الطلاب',
  directory_profiles: 'الدليل والملفات الشخصية',
  admissions_screen: 'القبول',
  screen_admit: 'الفرز والقبول',
  lecturers_staff: 'المحاضرون',
  faculty_staff: 'أعضاء هيئة التدريس',
  courses_curriculum: 'المقررات',
  curriculum_syllabus: 'المنهج وتوصيف المقررات',
  finance_billing: 'المالية',
  billing_collections: 'الفوترة والتحصيل',
  hr_personnel: 'الموارد البشرية',
  personnel_payroll: 'الموظفين والرواتب',
  reports_analytics: 'التحليلات',
  analytics_insights: 'التحليلات والرؤى',
  settings_config: 'الإعدادات',
  system_config: 'تكوين النظام',
  teaching_allocation: 'التدريس',
  course_allocation: 'تخصيص المقررات',
  reports_institutional: 'التقارير',
  institutional_data: 'البيانات المؤسسية',
  users_roles: 'المستخدمون والأدوار',
  security_access: 'الأمان والوصول',

  // Students Page
  students_management: 'إدارة الطلاب',
  students_description: 'إدارة ومراقبة جميع سجلات الطلاب المسجلين، الأداء الأكاديمي، وحالة الرسوم.',
  import_students: 'استيراد الطلاب',
  create_student: 'إنشاء طالب',
  total_students: 'إجمالي الطلاب',
  active_enrolled: 'مسجلين نشطين',
  pending_enrollment: 'تسجيل معلق',
  suspended_status: 'موقوف',
  graduated_status: 'خريج',
  students_list: 'قائمة الطلاب',
  search_students: 'بحث بالاسم، البريد الإلكتروني، الرقم الجامعي، الهاتف...',
  status: 'الحالة',
  fee_status: 'حالة الرسوم',
  program: 'البرنامج',
  semester_label: 'الفصل الدراسي',
  gender: 'الجنس',
  all_statuses: 'جميع الحالات',
  enrolled_status: 'مسجل',
  pending_status: 'معلق',
  suspended_label: 'موقوف',
  graduated_label: 'خريج',
  withdrawn: 'منسحب',
  all_fees: 'جميع الرسوم',
  paid: 'مدفوع',
  unpaid: 'غير مدفوع',
  partial: 'جزئي',
  all_programs: 'جميع البرامج',
  all_semesters: 'جميع الفصول',
  all_genders: 'جميع الأجناس',
  male: 'ذكر',
  female: 'أنثى',
  delete_student_record: 'حذف سجل الطالب',
  delete_student_description: 'هل أنت متأكد من حذف هذا الطالب؟ سيتم إلغاء تنشيط حساب المستخدم الخاص به.',
  student_deleted_success: 'تم حذف الطالب {matric_no} بنجاح.',
  failed_delete_student: 'فشل حذف الطالب.',
  student_account_activated: 'تم تنشيط حساب الطالب.',
  student_account_suspended: 'تم إيقاف حساب الطالب.',
  failed_update_status: 'فشل تحديث حالة حساب الطالب.',
  breadcrumb_students: 'الطلاب',

  // Admissions Page
  admissions_management: 'إدارة القبول',
  admissions_description: 'مراجعة ومعالجة طلبات قبول الطلاب، اعتماد المرشحين، وتحويلهم إلى طلاب مسجلين.',
  applications_list: 'قائمة الطلبات',
  search_applications: 'بحث بالاسم، البريد الإلكتروني، رقم الطلب...',
  create_application: 'إنشاء طلب',
  application_no: 'رقم الطلب',
  applicant_name: 'اسم المتقدم',
  program_applied: 'البرنامج المقدم له',
  application_date: 'تاريخ الطلب',
  application_status: 'حالة الطلب',
  pending_application: 'معلق',
  approved_application: 'معتمد',
  rejected_application: 'مرفوض',
  admitted_application: 'مقبول',
  review_application: 'مراجعة الطلب',
  convert_to_student: 'تحويل إلى طالب',
  application_approved: 'تم اعتماد الطلب بنجاح.',
  application_rejected: 'تم رفض الطلب بنجاح.',
  under_review: 'قيد المراجعة',
  all_students: 'جميع الطلاب',
  total_applications: 'إجمالي الطلبات',
  enrolled_admissions: 'الطلاب المسجلين',
  delete_application: 'حذف الطلب',
  delete_application_confirm: 'هل أنت متأكد من حذف هذا الطلب؟',
  breadcrumb_admissions: 'القبول',

  // Lecturers Page
  lecturers_management: 'إدارة المحاضرين',
  lecturers_description: 'إدارة أعضاء هيئة التدريس، المهام التدريسية، وتتبع الأداء الأكاديمي.',
  lecturers_list: 'قائمة المحاضرين',
  lecturers_directory: 'دليل المحاضرين',
  search_lecturers: 'بحث بالاسم، البريد الإلكتروني، القسم...',
  create_lecturer: 'إنشاء محاضر',
  lecturer_name: 'اسم المحاضر',
  lecturer_status: 'الحالة',
  active_lecturer: 'نشط',
  inactive_lecturer: 'غير نشط',
  courses_taught: 'المقررات المدرسة',
  on_leave: 'في إجازة',
  sabbatical: 'إجازة سباستيكال',
  terminated: 'منتهي العقد',
  full_time: 'دوام كامل',
  part_time: 'دوام جزئي',
  adjunct: 'محاضر زائر',
  visiting: 'زائر',
  total_faculty: 'إجمالي الهيئة',
  registered_academic_staff: 'أعضاء هيئة التدريس المسجلين',
  currently_lecturing: 'يقدم محاضرات حالياً',
  sabbatical_leave: 'إجازة سباستيكال',
  permanent_faculty: 'هيئة دائمة',
  part_time_adjunct: 'دوام جزئي / زائر',
  visiting_adjunct_staff: 'أعضاء هيئة زائرين',
  delete_lecturer: 'حذف سجل المحاضر',
  delete_lecturer_confirm: 'هل أنت متأكد من حذف هذا المحاضر؟ سيتم إلغاء تنشيط حساب المستخدم الخاص به.',
  lecturer_deleted: 'تم حذف المحاضر {name} بنجاح.',
  failed_delete_lecturer: 'فشل حذف سجل المحاضر.',
  lecturer_status_updated: 'تم تحديث حالة المحاضر بنجاح.',
  failed_update_lecturer_status: 'فشل تحديث حالة المحاضر.',
  reset_lecturer_password: 'إعادة تعيين كلمة مرور المحاضر',
  reset_password_description: 'تعيين كلمة مرور آمنة جديدة لحساب عضو هيئة التدريس هذا.',
  breadcrumb_lecturers: 'المحاضرون',

  // Assignments Page
  assignments_management: 'المهام التدريسية',
  assignments_description: 'إدارة مهام المقررات، جداول التدريس، وتخصيص القاعات.',
  assignments_list: 'قائمة المهام',
  search_assignments: 'بحث برمز المقرر، اسم المحاضر...',
  create_assignment: 'إنشاء مهمة',
  course_code: 'رمز المقرر',
  course_name: 'اسم المقرر',
  assigned_lecturer: 'المحاضر المعين',
  schedule: 'الجدول',
  room: 'القاعة',
  assignment_status: 'الحالة',
  active_assignment: 'نشط',
  completed_assignment: 'مكتمل',
  all_years: 'جميع السنوات',
  all_lecturers: 'جميع المحاضرين',
  all_courses: 'جميع المقررات',
  assigned: 'معين',
  cancelled: 'ملغي',
  total_assignments: 'إجمالي المهام',
  delete_assignment: 'حذف المهمة',
  delete_assignment_confirm: 'هل أنت متأكد من حذف هذه المهمة؟',
  assignment_deleted: 'تم حذف المهمة بنجاح.',
  failed_delete_assignment: 'فشل حذف المهمة.',
  semester_1: 'الفصل الأول',
  semester_2: 'الفصل الثاني',
  semester_3: 'الفصل الثالث',
  semester_4: 'الفصل الرابع',
  semester_5: 'الفصل الخامس',
  semester_6: 'الفصل السادس',
  breadcrumb_assignments: 'المهام',

  // Programs Page
  programs_management: 'البرامج الأكاديمية',
  programs_description: 'إدارة برامج الدرجة، هيكل المنهج، ومتطلبات البرنامج.',
  programs_list: 'قائمة البرامج',
  search_programs: 'بحث باسم البرنامج، الرمز...',
  create_program: 'إنشاء برنامج',
  program_name: 'اسم البرنامج',
  program_code: 'رمز البرنامج',
  program_level: 'المستوى',
  program_duration: 'المدة (سنوات)',
  credit_requirements: 'متطلبات الساعات المعتمدة',
  code: 'الرمز',
  program_name_label: 'اسم البرنامج',
  degree_level: 'مستوى الدرجة',
  duration_semesters: 'المدة (فصول)',
  total_credits: 'إجمالي الساعات المعتمدة',
  faculty_label: 'الكلية',
  program_status: 'الحالة',
  all_faculties: 'جميع الكليات',
  all_degree_levels: 'جميع مستويات الدرجة',
  bachelor: 'بكالوريوس',
  master: 'ماجستير',
  phd: 'دكتوراه',
  diploma: 'دبلوم',
  program_active: 'نشط',
  program_inactive: 'غير نشط',
  delete_program: 'حذف البرنامج',
  delete_program_confirm: 'هل أنت متأكد من حذف هذا البرنامج؟',
  program_deleted: 'تم حذف البرنامج {name}.',
  failed_delete_program: 'فشل حذف البرنامج الأكاديمي.',
  total_programs_stats: 'إجمالي البرامج',
  active_programs_stats: 'البرامج النشطة',
  total_students_stats: 'إجمالي الطلاب',
  total_courses_stats: 'إجمالي المقررات',
  faculties_count: 'عدد الكليات',
  archived: 'مؤرشف',
  actions: 'الإجراءات',
  view: 'عرض',
  breadcrumb_programs: 'البرامج',

  // Courses Page
  courses_management: 'إدارة المقررات',
  courses_description: 'إدارة كتالوج المقررات، المتطلبات السابقة، ومواد المقررات.',
  courses_list: 'قائمة المقررات',
  search_courses: 'بحث برمز المقرر، الاسم...',
  create_course: 'إنشاء مقرر',
  course_title: 'عنوان المقرر',
  course_credits: 'الساعات المعتمدة',
  course_prerequisites: 'المتطلبات السابقة',
  breadcrumb_courses: 'المقررات',

  // Semesters Page
  semesters_management: 'الفصول الدراسية',
  semesters_description: 'إدارة التقويم الأكاديمي، جداول الفصول، وفترات التسجيل.',
  semesters_list: 'قائمة الفصول',
  create_semester: 'إنشاء فصل دراسي',
  semester_name: 'اسم الفصل',
  start_date: 'تاريخ البدء',
  end_date: 'تاريخ الانتهاء',
  registration_period: 'فترة التسجيل',
  breadcrumb_semesters: 'الفصول',

  // Enrollments Page
  enrollments_management: 'تسجيل المقررات',
  enrollments_description: 'إدارة تسجيل الطلاب في المقررات، طلبات الحذف والإضافة، وحالة التسجيل.',
  enrollments_list: 'قائمة التسجيلات',
  search_enrollments: 'بحث بالطالب، المقرر...',
  create_enrollment: 'إنشاء تسجيل',
  enrollment_student: 'الطالب',
  enrollment_course: 'المقرر',
  enrollment_semester: 'الفصل الدراسي',
  enrollment_status: 'حالة التسجيل',
  breadcrumb_enrollments: 'التسجيل',

  // Transcripts Page
  transcripts_management: 'السجلات الأكاديمية',
  transcripts_description: 'عرض وإدارة السجلات الأكاديمية للطلاب، الدرجات، وتوليد كشوف الدرجات.',
  transcripts_list: 'قائمة السجلات',
  search_transcripts: 'بحث باسم الطالب، الرقم الجامعي...',
  generate_transcript: 'توليد كشف درجات',
  student_record: 'سجل الطالب',
  academic_performance: 'الأداء الأكاديمي',
  transcript_generated: 'تم توليد كشف الدرجات بنجاح.',
  breadcrumb_transcripts: 'السجلات',

  // Finance Pages
  finance_management: 'الإدارة المالية',
  finance_description: 'إدارة الرسوم الدراسية، الفواتير، المدفوعات، والتقارير المالية.',
  finance_list: 'قائمة المالية',
  search_finance: 'بحث برقم الفاتورة، الطالب...',
  create_invoice: 'إنشاء فاتورة',
  invoice_no: 'رقم الفاتورة',
  invoice_amount: 'المبلغ',
  invoice_due_date: 'تاريخ الاستحقاق',
  invoice_status: 'الحالة',
  payment_list: 'قائمة المدفوعات',
  search_payments: 'بحث برقم المعاملة، الطالب...',
  record_payment: 'تسجيل دفع',
  transaction_no: 'رقم المعاملة',
  payment_amount: 'المبلغ',
  payment_method: 'طريقة الدفع',
  payment_date: 'تاريخ الدفع',
  fees_management: 'إدارة الرسوم',
  fees_description: 'إدارة هيكل الرسوم، خطط الدفع، وإعفاءات الرسوم.',
  breadcrumb_finance: 'المالية',
  breadcrumb_fees: 'الرسوم',
  breadcrumb_payments: 'المدفوعات',
  breadcrumb_invoices: 'الفواتير',

  // Expenses Page
  expenses_management: 'إدارة المصروفات',
  expenses_description: 'تتبع وإدارة مصروفات الجامعة، الميزانيات، وتخصيص التكاليف.',
  expenses_list: 'قائمة المصروفات',
  search_expenses: 'بحث بنوع المصروف، التاريخ...',
  create_expense: 'إنشاء مصروف',
  expense_type: 'نوع المصروف',
  expense_category: 'الفئة',
  expense_amount: 'المبلغ',
  expense_date: 'التاريخ',
  expense_description: 'الوصف',
  breadcrumb_expenses: 'المصروفات',

  // Chart of Accounts Page
  chart_of_accounts: 'دليل الحسابات',
  chart_description: 'إدارة الحسابات المالية، رموز الحسابات، وهيكل المحاسبة.',
  accounts_list: 'قائمة الحسابات',
  search_accounts: 'بحث برمز الحساب، الاسم...',
  create_account: 'إنشاء حساب',
  account_code: 'رمز الحساب',
  account_name: 'اسم الحساب',
  account_type: 'نوع الحساب',
  parent_account: 'الحساب الرئيسي',
  breadcrumb_chart_of_accounts: 'دليل الحسابات',

  // Reports Page
  reports_management: 'التقارير',
  reports_description: 'عرض وتوليد تقارير متنوعة للتحليل الأكاديمي والمالي والإداري.',
  reports_list: 'قائمة التقارير',
  generate_report: 'توليد تقرير',
  report_type: 'نوع التقرير',
  date_range: 'نطاق التاريخ',
  export_report: 'تصدير التقرير',
  breadcrumb_reports: 'التقارير',

  // Settings - System
  system_settings: 'إعدادات النظام',
  system_settings_description: 'تكوين إعدادات النظام، التفضيلات، وتكوين التطبيق.',
  application_name: 'اسم التطبيق',
  timezone: 'المنطقة الزمنية',
  date_format: 'تنسيق التاريخ',
  time_format: 'تنسيق الوقت',
  language: 'اللغة',
  maintenance_mode: 'وضع الصيانة',
  save_settings: 'حفظ الإعدادات',
  breadcrumb_system_settings: 'إعدادات النظام',

  // Settings - Roles
  roles_management: 'الأدوار والصلاحيات',
  roles_description: 'إدارة أدوار المستخدمين، الصلاحيات، والتحكم في الوصول.',
  roles_list: 'قائمة الأدوار',
  create_role: 'إنشاء دور',
  role_name: 'اسم الدور',
  permissions: 'الصلاحيات',
  assign_permissions: 'تعيين الصلاحيات',
  delete_role: 'حذف الدور',
  delete_role_confirm: 'هل أنت متأكد من حذف هذا الدور؟',
  breadcrumb_roles: 'الأدوار',

  // Settings - Audit Log
  audit_log: 'سجل التدقيق',
  audit_log_description: 'عرض سجلات نشاط النظام، إجراءات المستخدمين، والأحداث الأمنية.',
  audit_logs_list: 'سجلات التدقيق',
  filter_logs: 'تصفية السجلات',
  user_action: 'إجراء المستخدم',
  event_type: 'نوع الحدث',
  ip_address: 'عنوان IP',
  timestamp: 'الطابع الزمني',
  breadcrumb_audit_log: 'سجل التدقيق',

  // Settings - Users
  users_management: 'إدارة المستخدمين',
  users_description: 'إدارة مستخدمي النظام، الحسابات، والوصول للمستخدمين.',
  users_list: 'قائمة المستخدمين',
  create_user: 'إنشاء مستخدم',
  user_name: 'اسم المستخدم',
  user_email: 'البريد الإلكتروني',
  user_role: 'دور المستخدم',
  user_status: 'حالة المستخدم',
  deactivate_user: 'إلغاء تنشيط المستخدم',
  activate_user: 'تنشيط المستخدم',
  reset_password: 'إعادة تعيين كلمة المرور',
  delete_user: 'حذف المستخدم',
  delete_user_confirm: 'هل أنت متأكد من حذف هذا المستخدم؟',
  breadcrumb_users: 'المستخدمون',

  // Reports Page Metrics
  program_distribution: 'توزيع البرامج',
  admission_pipeline: 'خط القبول',
  lecturer_assignments_reports: 'تعيينات المحاضرين',
  cohort_progression: 'تقدم الدفعات حسب الفصل',
  recent_payments_reports: 'المدفوعات الأخيرة',
  top_performers: 'أفضل الأداء الأكاديمي',
  program_leadership: 'قيادة البرنامج',
  student_academic_progression: 'التقدم الأكاديمي للطلاب',
  student_academic_progression_description: 'تتبع احتفاظ الطلاب وتقدمهم عبر الفصول.',
  no_cohort_data: 'لا توجد بيانات تقدم دفعات متاحة.',
  total_certificates_issued: 'إجمالي الشهادات المصدرة',

  // System Settings Page
  system_configuration_saved: 'تم حفظ تكوين النظام بنجاح.',
  total_accounts: 'إجمالي الحسابات',
  enrolled_students_system: 'الطلاب المسجلون',
  total_programs_system: 'إجمالي البرامج',
  total_courses_system: 'إجمالي المقررات',
  total_lecturers_system: 'إجمالي المحاضرين',
  active_assignments_system: 'التعيينات النشطة',
  php_version: 'إصدار PHP',
  laravel_version: 'إصدار Laravel',
  server_software: 'برنامج الخادم',
  database_driver: 'محرك قاعدة البيانات',
  database_name: 'اسم قاعدة البيانات',
  cache_driver: 'محرك التخزين المؤقت',
  queue_driver: 'محرف الطابور',
  timezone_system: 'المنطقة الزمنية',
  environment: 'البيئة',
  debug_mode: 'وضع التصحيح',
  system_configuration_diagnostics: 'تكوين النظام وتشخيص الخادم',
  system_institutional_configurations: 'تكوينات النظام والمؤسسة',
  system_config_description: 'إدارة بيانات المؤسسة، أقفال تسجيل البوابة، تواريخ الجلسة الأكاديمية، وصحة بيئة الخادم.',
  saving_changes: 'جاري الحفظ...',
  save_changes: 'حفظ التغييرات',
  institution_name: 'اسم المؤسسة',
  institution_motto: 'شعار المؤسسة',
  contact_email: 'البريد الإلكتروني للاتصال',
  contact_phone: 'رقم الهاتف',
  campus_address: 'عنوان الحرم الجامعي',
  academic_year: 'السنة الأكاديمية',
  current_term: 'الفصل الحالي',
  student_registration_enabled: 'تسجيل الطالب مفعل',
  course_enrollment_open: 'تسجيل المقرر مفتوح',
  maintenance_mode_system: 'وضع الصيانة',
  late_fee_percentage: 'نسبة رسوم التأخير',

  // Courses Page
  course_deleted: 'تم حذف المقرر {code} - {name}.',
  failed_delete_course: 'فشل حذف المقرر.',
  general_program: 'البرنامج العام',
  lecturer_assignments_label: 'تعيينات المحاضرين',
  all_semesters_filter: 'جميع الفصول',
  all_levels_filter: 'جميع المستويات',
  all_programs_filter: 'جميع البرامج',
  semester_prefix: 'فصل',
  delete_course: 'حذف المقرر',
  delete_course_confirm: 'هل أنت متأكد من حذف هذا المقرر؟',
  active_courses_stats: 'المقررات النشطة',
  total_assignments_stats: 'إجمالي التعيينات',
  total_credits_stats: 'إجمالي الساعات المعتمدة',

  // Semesters Page
  semester_curricula_cohorts: 'مناهج الفصول والدفعات',
  semester_overview_cohort: 'نظرة عامة على الفصول وتوزيع الدفعات',
  semester_description: 'عرض توزيع المناهج حسب الفصل، أحجام الدفعات، وتخصيص المقررات عبر جميع البرامج الأكاديمية.',
  total_semesters_stats: 'إجمالي الفصول',
  active_cohorts_stats: 'الدفعات النشطة',
  total_courses_offered_stats: 'إجمالي المقررات المقدمة',
  total_enrolled_students_stats: 'إجمالي الطلاب المسجلين',
  filter_by_program: 'تصفية حسب البرنامج',
  all_programs_semesters: 'جميع البرامج',
  semester_label_page: 'الفصل',
  level_label: 'المستوى',
  courses_count_label: 'المقررات',
  students_count_label: 'الطلاب',
  total_credits_label: 'إجمالي الساعات المعتمدة',
  view_courses: 'عرض المقررات',
  active_status: 'نشط',
  program_semesters: 'فصول البرنامج',
  workload: 'عبء العمل',
  curriculum_courses: 'مقررات المنهج',
  no_courses_configured: 'لم يتم تكوين مقررات بعد.',

  // Enrollments Page
  total_enrolled_stats: 'إجمالي المسجلين',
  active_students_enrollments: 'الطلاب النشطون',
  pending_enrollments_stats: 'التسجيلات المعلقة',
  graduated_students_enrollments: 'الطلاب الخريجون',
  suspended_students_enrollments: 'الطلاب المعلقون',
  matric_number: 'الرقم الجامعي',
  enrollment_status_page: 'حالة التسجيل',
  current_semester_enrollment: 'الفصل الحالي',
  fee_status_enrollment: 'حالة الرسوم',
  enrollment_date_label: 'تاريخ التسجيل',
  gpa_label_enrollment: 'المعدل التراكمي',
  enrollment_active: 'نشط',
  enrollment_pending: 'معلق',
  enrollment_graduated: 'خريج',
  enrollment_suspended: 'معلق',
  enrolled_status_enrollment: 'مسجل',
  pending_fee_status: 'معلق',
  paid_fee_status: 'مدفوع',
  partial_fee_status: 'جزئي',
  view_enrollment: 'عرض التسجيل',
  unassigned: 'غير معين',
  term: 'الفصل',
  enroll_student: 'تسجيل طالب',
  enrollment_roster: 'قائمة التسجيل',

  // Transcripts Page
  total_students_transcripts: 'إجمالي الطلاب',
  avg_institution_gpa: 'متوسط المعدل التراكمي للمؤسسة',
  total_grades_recorded: 'إجمالي الدرجات المسجلة',
  certificates_issued: 'الشهادات المصدرة',
  grades_count_label: 'الدرجات',
  certificates_count_label: 'الشهادات',
  transcript_student_name: 'اسم الطالب',
  transcript_program: 'البرنامج',
  transcript_term: 'الفصل',
  transcript_gpa: 'المعدل التراكمي',
  view_transcript: 'عرض السجل الأكاديمي',
  generate_transcript_button: 'توليد كشف درجات',
  cumulative_gpa: 'المعدل التراكمي',
  issued: 'مصدرة',

  // Finance Overview Page
  financial_solvency_revenue: 'الملاءة المالية ونظرة عامة على الإيرادات',
  finance_bursar_center: 'مركز التحكم المالي ومكتب الخزينة',
  finance_description: 'تقييم رسوم الدراسية في الوقت الفعلي، تحصيل الرسوم، التحقق من دفعات الطلاب، وتدفق السيولة النقدية.',
  total_invoiced_finance: 'إجمالي الفواتير',
  total_collected_finance: 'إجمالي المحصل',
  total_outstanding_finance: 'إجمالي المستحق',
  pending_payments_finance: 'المدفوعات المعلقة',
  overdue_invoices_finance: 'الفواتير المتأخرة',
  recent_transactions: 'المعاملات الأخيرة',
  recent_invoices_finance: 'الفواتير الأخيرة',
  revenue_by_payment_method: 'الإيرادات حسب طريقة الدفع',
  invoices_by_type: 'الفواتير حسب النوع',
  transaction_no_label: 'رقم المعاملة',
  payment_date_label: 'تاريخ الدفع',
  invoice_no_label: 'رقم الفاتورة',
  invoice_title: 'العنوان',
  invoice_type: 'النوع',
  paid_amount: 'المبلغ المدفوع',
  due_date_label: 'تاريخ الاستحقاق',
  view_all_payments: 'عرض جميع المدفوعات',
  view_all_invoices: 'عرض جميع الفواتير',
  manage_fees: 'إدارة الرسوم',
  chart_of_accounts_label: 'دليل الحسابات',
  no_payment_transactions: 'لم يتم تسجيل معاملات دفع بعد.',
  no_invoices_recorded: 'لم يتم تسجيل فواتير بعد.',
  recent_invoices_desc: 'أحدث فواتير الرسوم الدراسية والرسوم المصدرة للطلاب.',

  // Fees Page
  fee_schedules: 'جداول الرسوم',
  fee_schedules_description: 'إدارة هياكل رسوم الطلاب، خطط الدفع، وتقييمات الرسوم.',
  total_students_fees: 'إجمالي الطلاب',
  fully_paid_students: 'مدفوع بالكامل',
  partial_students: 'جزئي',
  unpaid_students: 'غير مدفوع',
  total_receivables: 'إجمالي المستحقات',
  matric_no_fees: 'الرقم الجامعي',
  total_billed: 'إجمالي المفوتر',
  total_paid_fees: 'إجمالي المدفوع',
  balance: 'الرصيد',
  fee_status_filter: 'حالة الرسوم',
  all_fee_statuses: 'جميع حالات الرسوم',
  fully_paid_status: 'مدفوع بالكامل',
  partial_status: 'جزئي',
  unpaid_status: 'غير مدفوع',
  program_filter_fees: 'البرنامج',
  all_programs_fees: 'جميع البرامج',
  view_student_profile: 'عرض الملف الشخصي',
  institutional_tuition_schedule: 'جدول الرسوم الدراسي المؤسسي (السنة الأكاديمية القياسية 2026/2027)',
  fees_list_label: 'دليل رسوم الطلاب',
  search_fees: 'بحث بالرقم الجامعي، اسم الطالب...',
  approved_fee_schedule: 'جدول الرسوم المعتمد حسب برنامج الدرجة بالكلية.',
  undergraduate_tuition: 'رسوم الدراسة الجامعية',
  postgraduate_tuition: 'رسوم الدراسات العليا',
  one_time_institutional_fees: 'الرسوم المؤسسية لمرة واحدة',
  includes_registration: 'يشمل تسجيل المقرر، الوصول إلى المختبر، مكتبة الحرم، ورسوم الامتحانات.',
  includes_thesis: 'يشمل إشراف الأطروح المتقدمة، مستود المجلات، والمرافق المخبرية.',
  admission_matriculation: 'القبول والتسجيل',
  graduation_transcript: 'التخرج والسجل الأكاديمي',
  bachelor: 'بكالوريوس',
  master: 'ماجستير',
  phd: 'دكتوراه',

  // Payments Page
  payments_roster: 'سجل المدفوعات',
  payments_description: 'تتبع وإدارة جميع معاملات دفع الطلاب، طرق الدفع، والمطابقة.',
  payments_list: 'قائمة المدفوعات',
  search_payments: 'بحث برقم المعاملة، اسم الطالب...',
  transaction_no_payments: 'رقم المعاملة',
  payment_amount_payments: 'المبلغ',
  payment_method_payments: 'طريقة الدفع',
  payment_date_payments: 'تاريخ الدفع',
  student_name_payments: 'اسم الطالب',
  program_payments: 'البرنامج',
  status_payments: 'الحالة',
  all_statuses_payments: 'جميع الحالات',
  completed_payment: 'مكتمل',
  pending_payment: 'معلق',
  failed_payment: 'فشل',
  refunded_payment: 'مسترد',
  record_payment: 'تسجيل دفع',
  payment_method_filter: 'طريقة الدفع',
  all_payment_methods: 'جميع الطرق',
  total_collected: 'إجمالي المحصل',
  pending_review: 'قيد المراجعة',
  todays_collections: 'تحصيلات اليوم',
  total_transactions: 'إجمالي المعاملات',
  approve: 'موافقة',
  reject: 'رفض',
  enter_payment_details: 'أدخل تفاصيل معاملة الدفع المستلمة من الطالب.',
  select_student: 'اختر الطالب',
  receipt_reference_note: 'إيصال / ملاحظة مرجعية',
  saving: 'جاري الحفظ...',
  no_due_date: 'لا يوجد تاريخ استحقاق',
  overdue: 'متأخر',
  paid_invoice: 'مدفوع',
  partial_paid_invoice: 'جزئي',
  items: 'العناصر',
  view: 'عرض',
  total_invoiced: 'إجمالي الفواتير',
  total_paid: 'إجمالي المدفوع',
  outstanding_due: 'المستحقات المتأخرة',
  issue_invoice: 'إصدار فاتورة',
  total_invoices: 'إجمالي الفواتير',
  overdue_invoices: 'الفواتير المتأخرة',
  bills: 'فواتير',
  issue_student_invoice: 'إصدار فاتورة طالب',
  create_invoice_description: 'إنشاء فاتورة رسمية مخصصة لسجل رسوم الطالب.',
  invoice_title: 'عنوان الفاتورة',
  fee_category: 'فئة الرسوم',
  line_items: 'بنود الفاتورة',
  add_item: 'إضافة عنصر',
  add_line_items_description: 'أضف بنود لتفصيل رسوم الفاتورة.',
  computed_amount: 'المبلغ المحسوب',
  delete_invoice: 'حذف الفاتورة',
  delete_invoice_description: 'هل أنت متأكد من أنك تريد حذف هذه الفاتورة؟ لا يمكن حذف الفواتير التي تم تحصيل المدفوعات منها.',

  // Invoices Page
  invoices_list_page: 'الفواتير',
  invoices_description: 'إدارة فواتير الرسوم الدراسية للطلاب، تقييمات الرسوم، وسجلات الفوترة.',
  invoices_list_label: 'قائمة الفواتير',
  search_invoices: 'بحث برقم الفاتورة، اسم الطالب...',
  invoice_no_invoices: 'رقم الفاتورة',
  invoice_title_invoices: 'العنوان',
  invoice_type_invoices: 'النوع',
  invoice_amount_invoices: 'المبلغ',
  due_date_invoices: 'تاريخ الاستحقاق',
  paid_amount_invoices: 'المبلغ المدفوع',
  balance_invoices: 'الرصيد',
  status_invoices: 'الحالة',
  all_statuses_invoices: 'جميع الحالات',
  draft_invoice: 'مسودة',
  sent_invoice: 'مرسلة',
  partial_paid_invoice: 'مدفوع جزئياً',
  paid_invoice: 'مدفوع',
  overdue_invoice: 'متأخرة',
  cancelled_invoice: 'ملغاة',
  create_invoice: 'إنشاء فاتورة',
  invoice_type_filter: 'نوع الفاتورة',
  all_invoice_types: 'جميع الأنواع',

  // Expenses Page
  expenses_management_page: 'إدارة المصروفات',
  expenses_description_page: 'تتبع وإدارة مصروفات الجامعة، الميزانيات، وتخصيص التكاليف.',
  expenses_list_page: 'قائمة المصروفات',
  search_expenses_page: 'بحث بنوع المصروف، التاريخ...',
  create_expense_page: 'إنشاء مصروف',
  expense_type_page: 'نوع المصروف',
  expense_category_page: 'الفئة',
  expense_amount_page: 'المبلغ',
  expense_date_page: 'التاريخ',
  expense_description_page: 'الوصف',
  all_expense_types: 'جميع الأنواع',
  all_categories: 'جميع الفئات',

  // Chart of Accounts Page
  chart_of_accounts_page: 'دليل الحسابات',
  chart_description_page: 'إدارة الحسابات المالية، رموز الحسابات، وهيكل المحاسبة.',
  accounts_list_page: 'قائمة الحسابات',
  search_accounts_page: 'بحث برمز الحساب، الاسم...',
  create_account_page: 'إنشاء حساب',
  account_code_page: 'رمز الحساب',
  account_name_page: 'اسم الحساب',
  account_type_page: 'نوع الحساب',
  parent_account_page: 'الحساب الرئيسي',
  all_account_types: 'جميع الأنواع',
  asset: 'أصل',
  liability: 'التزام',
  equity: 'حقوق الملكية',
  revenue: 'إيراد',
  expense: 'مصروف',

  // Expenses Page - Detailed
  university_expense_management: 'إدارة مصروفات الجامعة',
  university_expense_description: 'تتبع المصروفات التشغيلية والأكاديمية مقابل دليل حسابات الجامعة مع الموافقات متعددة المستويات.',
  finance_overview: 'نظرة عامة مالية',
  record_expense: 'تسجيل مصروف',
  total_expense: 'إجمالي المصروفات',
  pending_approval_expenses: 'معلق للموافقة',
  this_month_expenses: 'هذا الشهر',
  total_vouchers: 'إجمالي الإيصالات',
  rejected_expenses: 'مرفوض',
  expense_vouchers: 'إيصالات المصروفات',
  search_expenses_description: 'بحث برقم المصروف، العنوان، المورد، سطر الميزانية، أو الحساب...',
  expense_no_column: 'رقم المصروف',
  expense_column: 'المصروف',
  account_column: 'الحساب',
  amount_column: 'المبلغ',
  date_column: 'التاريخ',
  budget_line_column: 'سطر الميزانية',
  status_column: 'الحالة',
  actions_column: 'الإجراءات',
  mark_paid: 'تحديد كمدفوع',
  approve_expense: 'موافقة',
  reject_expense: 'رفض',
  view_expense: 'عرض',
  all_statuses_filter: 'جميع الحالات',
  draft_status: 'مسودة',
  pending_approval_status: 'معلق للموافقة',
  approved_status: 'معتمد',
  paid_status: 'مدفوع',
  rejected_status: 'مرفوض',
  cancelled_status: 'ملغي',
  all_accounts_filter: 'جميع الحسابات',
  record_university_expense: 'تسجيل مصروف جامعي',
  record_expense_description: 'تقديم إيصال مصروف. المصروفات المقدمة تدخل سلسلة الموافقة متعددة المستويات.',
  expense_title: 'عنوان المصروف',
  expense_title_placeholder: 'مثال: فاتورة الكهرباء للحرم الرئيسي',
  account_select: 'الحساب',
  select_account: 'اختر الحساب...',
  amount_dollar: 'المبلغ ($)',
  amount_placeholder: '1500.00',
  expense_date_label: 'تاريخ المصروف',
  pick_date: 'اختر التاريخ',
  vendor_payee: 'المورد / المستفيد',
  vendor_placeholder: 'مثال: جوليس الكهربائية',
  budget_line_label: 'سطر الميزانية',
  budget_line_placeholder: 'مثال: العمليات',
  expense_status_label: 'الحالة',
  submit_for_approval: 'تقديم للموافقة',
  save_as_draft: 'حفظ كمسودة',
  description_label: 'الوصف',
  description_placeholder: 'تفاصيل حول هذا المصروف...',
  notes_label: 'ملاحظات',
  record_expense_button: 'تسجيل المصروف',
  saving: 'جاري الحفظ...',
  reject_expense_title: 'رفض المصروف',
  reject_expense_description: 'توفير سبب لرفض {expense_no}. الرفض يتطلب تعليقاً.',
  rejection_reason: 'سبب الرفض',
  rejection_reason_placeholder: 'اشرح سبب رفض هذا المصروف...',
  confirm_reject: 'رفض',
  expense_deleted: 'تم حذف المصروف {expense_no}.',
  failed_delete_expense: 'فشل حذف المصروف.',
  expense_approved: 'تمت الموافقة على المصروف {expense_no}.',
  approval_failed: 'فشلت الموافقة.',
  expense_marked_paid: 'تم تحديد المصروف {expense_no} كمدفوع.',
  failed_mark_paid: 'فشل تحديد المصروف كمدفوع.',
  expense_rejected: 'تم رفض المصروف {expense_no}.',
  failed_reject_expense: 'فشل رفض المصروف.',
  breadcrumb_dashboard: 'لوحة التحكم',
  breadcrumb_finance: 'المالية',
  breadcrumb_expenses: 'المصروفات',

  // Chart of Accounts Page - Detailed
  dashboard_breadcrumb: 'لوحة التحكم',
  finance_breadcrumb: 'المالية',
  chart_of_accounts_breadcrumb: 'دليل الحسابات',
  total_accounts_coa: 'إجمالي الحسابات',
  active_accounts_coa: 'الحسابات النشطة',
  inactive_accounts_coa: 'الحسابات غير النشطة',
  account_groups_coa: 'مجموعات الحسابات',
  configured_accounts_roster: 'سجل الحسابات المكونة',
  search_accounts_description: 'بحث برمز الحساب، الاسم، النوع، الحالة...',
  account_name_column: 'اسم الحساب',
  account_type_column: 'النوع',
  normal_balance_column: 'الرصيد الطبيعي',
  account_status_column: 'الحالة',
  transactions_column: 'المعاملات',
  account_actions_column: 'الإجراءات',
  debit_balance: 'مدين',
  credit_balance: 'دائن',
  active_status_coa: 'نشط',
  inactive_status_coa: 'غير نشط',
  add_account: 'إضافة حساب',
  add_account_description: 'إنشاء حساب جديد في دليل حسابات الجامعة.',
  account_group: 'مجموعة الحساب',
  select_account_group: 'اختر مجموعة الحساب...',
  account_code_label: 'رمز الحساب',
  account_code_placeholder: 'مثال: 4030',
  suggested_code: 'الرمز المقترح',
  available: 'متاح',
  account_codes_are_4_digit: 'رموز الحسابات هي أرقام مكونة من 4 خانات.',
  code_already_in_use: 'رمز الحساب هذا مستخدم بالفعل.',
  available_within_range: 'متاح — ضمن {group} ({range})',
  account_name_label_coa: 'اسم الحساب',
  account_name_placeholder: 'مثال: إيرادات الرسوم الدراسية — برنامج جديد',
  account_type_label_coa: 'نوع الحساب',
  normal_balance_label_coa: 'الرصيد الطبيعي',
  auto_derived_from_group: 'مشتق تلقائياً من المجموعة',
  description_label_coa: 'الوصف',
  description_placeholder_coa: 'تفاصيل اختيارية حول هذا الحساب...',
  status_label_coa: 'الحالة',
  cancel_button: 'إلغاء',
  create_account_button: 'إنشاء الحساب',
  account_created_success: 'تم إنشاء الحساب بنجاح.',
  unable_create_account: 'غير قادر على إنشاء الحساب. راجع الأخطاء أدناه.',
  edit_account: 'تعديل الحساب',
  account_has_transactions: 'لديه معاملات مرسلة، لذا لا يمكن تغيير رمز الحساب ومجموعته.',
  code_locks_transactions: 'يتم قفل الرمز بمجرد أن يكون للحساب معاملات مرسلة.',
  account_updated_success: 'تم تحديث الحساب بنجاح.',
  unable_update_account: 'غير قادر على تحديث الحساب. راجع الأخطاء أدناه.',
  save_changes_button: 'حفظ التغييرات',
  account_details: 'تفاصيل الحساب',
  account_information: 'معلومات الحساب',
  account_code_info: 'رمز الحساب',
  account_group_info: 'مجموعة الحساب',
  type_info: 'النوع',
  normal_balance_info: 'الرصيد الطبيعي',
  code_range_info: 'نطاق الرمز',
  status_info: 'الحالة',
  description_info: 'الوصف',
  no_description_provided: 'لم يتم توفير وصف.',
  created_info: 'تم الإنشاء',
  last_updated: 'آخر تحديث',
  financial_activity: 'النشاط المالي',
  total_credits: 'إجمالي الدائنين',
  total_debits: 'إجمالي المدينين',
  transactions_info: 'المعاملات',
  posted: 'مرسلة',
  recent_transactions: 'المعاملات الأخيرة',
  account_history: 'سجل الحساب',
  action_history: 'الإجراء',
  changes_history: 'التغييرات',
  actor_history: 'الممثل',
  timestamp_history: 'الطابع الزمني',
  system_badge: 'النظام',
  view_transactions: 'عرض المعاملات',
  toggle_status: 'تبديل الحالة',
  delete_account: 'حذف الحساب',
  account_type_asset: 'أصل',
  account_type_liability: 'التزام',
  account_type_equity: 'حقوق الملكية',
  account_type_revenue: 'إيراد',
  account_type_expense: 'مصروف',
  filter_by_group: 'المجموعة',
  filter_by_type: 'النوع',
  filter_by_balance: 'الرصيد الطبيعي',
  filter_by_status_coa: 'الحالة',
  all_groups: 'جميع المجموعات',
  all_types_coa: 'جميع الأنواع',
  all_balances: 'جميع الأرصدة',
  all_statuses_coa: 'جميع الحالات',
  assets: 'الأصول',
  liabilities: 'الالتزامات',
  equity: 'حقوق الملكية',
  revenue: 'الإيرادات',
  expenses_direct_academic: 'المصروفات (أكاديمية مباشرة)',
  expenses_operating: 'المصروفات (تشغيلية)',
  finance_costs_other: 'تكاليف التمويل وغيرها',

  // Users Page - Detailed
  user_management_access_control: 'إدارة المستخدمين والتحكم في الوصول',
  user_management_description: 'توفير تسجيلات دخول النظام، تعيين الأدوار المؤسسية، تنشيط/إلغاء تنشيط بيانات الاعتماد، وإعادة تعيين مفاتيح الأمان.',
  roles_permissions: 'الأدوار والصلاحيات',
  create_user_button: 'إنشاء مستخدم',
  total_users_stats: 'إجمالي المستخدمين',
  active_accounts_stats: 'الحسابات النشطة',
  super_admins_stats: 'المسؤولون الرئيسيون',
  faculty_lecturers_stats: 'محاضري هيئة التدريس',
  enrolled_students_stats: 'الطلاب المسجلون',
  system_accounts_roster: 'سجل حسابات النظام',
  search_users_description: 'بحث بالاسم، البريد الإلكتروني...',
  user_account_column: 'حساب المستخدم',
  assigned_role_column: 'الدور المعين',
  account_status_column: 'حالة الحساب',
  created_on_column: 'تاريخ الإنشاء',
  password_button: 'كلمة المرور',
  edit_button: 'تعديل',
  delete_button: 'حذف',
  role_filter: 'الدور',
  all_roles_filter: 'جميع الأدوار',
  super_admin_role: 'مسؤول رئيسي',
  registrar_role: 'مسجل',
  finance_role: 'مالي',
  hr_role: 'موارد بشرية',
  lecturer_role: 'محاضر',
  student_role: 'طالب',
  status_filter_users: 'الحالة',
  all_statuses_users: 'جميع الحالات',
  active_status_users: 'نشط',
  deactivated_status: 'غير نشط',
  provision_new_user: 'توفير مستخدم جديد',
  provision_user_description: 'إنشاء حساب مؤسسي مصادق عليه.',
  full_name: 'الاسم الكامل',
  full_name_placeholder: 'مثال: د. أحمد حسن',
  user_email_label: 'البريد الإلكتروني',
  email_placeholder: 'مثال: ahmed.hassan@uct.edu',
  password_label: 'كلمة المرور',
  password_placeholder: 'أدخل كلمة مرور آمنة',
  user_role_label: 'الدور',
  select_role: 'اختر الدور...',
  account_active: 'الحساب نشط',
  create_user_button_modal: 'إنشاء المستخدم',
  user_created_success: 'تم إنشاء المستخدم بنجاح.',
  failed_create_user: 'فشل إنشاء المستخدم.',
  edit_user: 'تعديل المستخدم',
  edit_user_description: 'تحديث معلومات المستخدم وإعدادات الوصول.',
  update_user: 'تحديث المستخدم',
  user_updated_success: 'تم تحديث المستخدم بنجاح.',
  failed_update_user: 'فشل تحديث المستخدم.',
  reset_password_title: 'إعادة تعيين كلمة المرور',
  reset_password_description: 'تعيين كلمة مرور آمنة جديدة لحساب المستخدم هذا.',
  new_password: 'كلمة المرور الجديدة',
  confirm_password: 'تأكيد كلمة المرور',
  reset_password_button: 'إعادة تعيين كلمة المرور',
  password_reset_success: 'تم إعادة تعيين كلمة المرور بنجاح.',
  failed_reset_password: 'فشل إعادة تعيين كلمة المرور.',
  delete_user_title: 'حذف المستخدم',
  delete_user_description: 'هل أنت متأكد من حذف هذا المستخدم؟ لا يمكن التراجع عن هذا الإجراء.',
  user_deleted_success: 'تم حذف المستخدم بنجاح.',
  failed_delete_user: 'فشل حذف المستخدم.',
  user_status_updated: 'تم تحديث حالة المستخدم.',
  failed_update_user_status: 'فشل تحديث حالة المستخدم.',
  breadcrumb_settings: 'الإعدادات',
  breadcrumb_system: 'النظام',
  breadcrumb_users: 'إدارة المستخدمين',

  // Roles Page - Detailed
  roles_permissions_management: 'الأدوار وصلاحيات الوصول',
  roles_permissions_description: 'إدارة هرميات الأدوار، تكوين صلاحيات الوحدة الدقيقة، وتدقيق حسابات المستخدمين المعينة.',
  users_roster: 'سجل المستخدمين',
  create_role_button: 'إنشاء دور',
  total_roles_stats: 'إجمالي الأدوار',
  system_core_roles: 'أدوار النظام الأساسية',
  custom_roles_stats: 'الأدوار المخصصة',
  defined_privileges: 'الصلاحيات المحددة',
  assigned_users_stats: 'المستخدمون المعينون',
  configured_roles_roster: 'سجل الأدوار المكونة',
  search_roles_description: 'بحث باسم الدور، الرمز، الوصف...',
  role_name_column: 'اسم الدور',
  description_column: 'الوصف',
  permissions_column: 'الصلاحيات',
  assigned_users_column: 'المستخدمون المعينون',
  no_description_provided_role: 'لم يتم توفير وصف.',
  privileges_count: 'الصلاحيات',
  accounts_count: 'حسابات',
  view_role: 'عرض',
  edit_role: 'تعديل',
  delete_role_button: 'حذف',
  delete_custom_role: 'حذف الدور المخصص',
  delete_role_description: 'هل أنت متأكد من حذف هذا الدور المخصص؟ سيتم إلغاء جميع الصلاحيات المرتبطة به.',
  role_deleted_success: 'تم حذف الدور {name}.',
  failed_delete_role: 'فشل حذف الدور.',
  breadcrumb_roles_page: 'الأدوار والصلاحيات',

  // Audit Log Page - Detailed
  security_audit_trail_log: 'سجل التدقيق والأمان',
  audit_log_description: 'سجل شامل لجميع الأحداث الإدارية، مصادقات المستخدمين، الإجراءات المالية، وتعديلات السجلات.',
  users_roster_link: 'سجل المستخدمين',
  total_logged_events: 'إجمالي الأحداث المسجلة',
  events_today: 'أحداث اليوم',
  security_events: 'أحداث الأمان',
  active_sessions: 'الجلسات النشطة',
  security_audit_records: 'سجلات التدقيق الأمني',
  search_audit_description: 'بحث بالمبتدئ، المورد، عنوان IP...',
  initiator_column: 'المبتدئ',
  event_action_column: 'إجراء الحدث',
  target_entity_column: 'الكيان / المورد المستهدف',
  network_device_column: 'الشبكة والجهاز',
  status_column_audit: 'الحالة',
  timestamp_column_audit: 'الطابع الزمني',
  event_category_filter: 'فئة الحدث',
  all_events_filter: 'جميع الأحداث',
  settings_updated: 'تحديثات الإعدادات',
  payment_verified: 'الدفاع تم التحقق منه',
  course_created: 'تم إنشاء المقرر',
  admission_approved: 'القبول معتمد',
  grade_submitted: 'تم تقديم الدرجة',
  invoice_issued: 'تم إصدار الفاتورة',
  user_created_audit: 'تم إنشاء المستخدم',
  completed_status_audit: 'مكتمل',
  pending_status_audit: 'معلق',
  failed_status_audit: 'فشل',
  breadcrumb_audit_log_page: 'سجل التدقيق',

  // Settings Pages
  settings_page: 'الإعدادات',
  settings_description: 'إدارة ملفك الشخصي وإعدادات الحساب',
  profile_settings: 'الملف الشخصي',
  profile_settings_description: 'تحديث اسمك وعنوان بريدك الإلكتروني',
  security_settings: 'الأمان',
  appearance_settings: 'المظهر',
  appearance_settings_description: 'تحديث إعدادات المظهر لحسابك',
  language_settings: 'اللغة',
  language_settings_description: 'اختر اللغة المفضلة للواجهة',
  name_label: 'الاسم',
  full_name_placeholder: 'الاسم الكامل',
  email_address_label: 'عنوان البريد الإلكتروني',
  email_address_placeholder: 'عنوان البريد الإلكتروني',
  save_button: 'حفظ',
  update_profile_button: 'تحديث الملف الشخصي',
  email_unverified: 'عنوان بريدك الإلكتروني غير موثق.',
  resend_verification_email: 'انقر هنا لإعادة إرسال بريد التحقق.',
  verification_link_sent: 'تم إرسال رابط تحقق جديد إلى عنوان بريدك الإلكتروني.',
  current_password_label: 'كلمة المرور الحالية',
  current_password_placeholder: 'كلمة المرور الحالية',
  new_password_label: 'كلمة المرور الجديدة',
  new_password_placeholder: 'كلمة المرور الجديدة',
  confirm_password_label: 'تأكيد كلمة المرور',
  confirm_password_placeholder: 'تأكيد كلمة المرور',
  update_password_button: 'تحديث كلمة المرور',
  security_description: 'تأكد من أن حسابك يستخدم كلمة مرور طويلة وعشوائية للبقاء آمناً',
  select_language: 'اختر اللغة',
  english_language: 'الإنجليزية',
  arabic_language: 'العربية',
  language_saved: 'تم حفظ تفضيل اللغة بنجاح.',
  profile_updated: 'تم تحديث الملف الشخصي بنجاح.',
  password_updated: 'تم تحديث كلمة المرور بنجاح.',
  settings_breadcrumb: 'الإعدادات',
  profile_breadcrumb: 'الملف الشخصي',
  security_breadcrumb: 'الأمان',
  appearance_breadcrumb: 'المظهر',
  language_breadcrumb: 'اللغة',
  update_password_label: 'تحديث كلمة المرور',
  settings_menu: 'الإعدادات',
  profile_menu: 'الملف الشخصي',
  security_menu: 'الأمان',
  appearance_menu: 'المظهر',
  language_menu: 'اللغة',

  // Navigation
  nav_platform: 'المنصة',
  nav_dashboard: 'لوحة التحكم',
  nav_students: 'الطلاب',
  nav_admissions: 'القبول',
  nav_lecturers: 'المحاضرين',
  nav_assignments: 'المهام',
  nav_academic: 'الأكاديمي',
  nav_programs: 'البرامج',
  nav_courses: 'المقررات',
  nav_semesters: 'الفصول',
  nav_enrollments: 'التسجيل',
  nav_transcripts: 'السجلات الأكاديمية',
  nav_finance: 'المالية',
  nav_finance_overview: 'نظرة عامة',
  nav_fees: 'الرسوم',
  nav_payments: 'المدفوعات',
  nav_invoices: 'الفواتير',
  nav_expenses: 'المصروفات',
  nav_chart_of_accounts: 'دليل الحسابات',
  nav_reports: 'التقارير',
  nav_settings: 'الإعدادات',
  nav_general_settings: 'الإعدادات العامة',
  nav_user_management: 'إدارة المستخدمين',
  nav_roles_permissions: 'الأدوار والصلاحيات',
  nav_audit_log: 'سجل التدقيق',
  nav_finance_expenses: 'المصروفات',
  nav_all_expenses: 'جميع المصروفات',
  nav_approvals: 'الموافقات',
  nav_my_courses: 'مقرراتي',
  nav_attendance: 'الحضور',
  nav_gradebook: 'دفتر الدرجات',
  nav_materials: 'المواد',
  nav_grades: 'الدرجات',
  nav_documents: 'الوثائق',
  nav_certificates: 'الشهادات',

  // User Menu
  menu_settings: 'الإعدادات',
  menu_logout: 'تسجيل الخروج',
};

export default ar;
