const en = {
  // Admissions & Students
  admission: 'Admission',
  applicant: 'Applicant',
  student: 'Student',
  student_id: 'Student ID',
  enrollment: 'Enrollment',
  transfer: 'Transfer',
  withdrawal: 'Withdrawal',
  graduate: 'Graduate',

  // Academic Structure
  faculty_college: 'Faculty / College',
  department: 'Department',
  program_major: 'Program / Major',
  course: 'Course',
  credit_hours: 'Credit Hours',
  semester: 'Semester',
  academic_year: 'Academic Year',
  prerequisite: 'Prerequisite',
  syllabus: 'Syllabus',
  study_plan: 'Study Plan',

  // Registration & Timetable
  course_registration: 'Course Registration',
  add_drop: 'Add/Drop',
  section: 'Section',
  timetable: 'Timetable',
  lecture_hall: 'Lecture Hall',
  attendance: 'Attendance',
  absence: 'Absence',
  academic_advisor: 'Academic Advisor',

  // Exams & Grades
  exam: 'Exam',
  midterm: 'Midterm',
  final_exam: 'Final Exam',
  grade: 'Grade',
  gpa: 'GPA',
  semester_gpa: 'Semester GPA',
  transcript: 'Transcript',
  academic_probation: 'Academic Probation',
  incomplete: 'Incomplete',
  result: 'Result',

  // Faculty & HR
  instructor_lecturer: 'Instructor / Lecturer',
  professor: 'Professor',
  teaching_assistant: 'Teaching Assistant',
  employee: 'Employee',
  payroll: 'Payroll',
  leave: 'Leave',
  contract: 'Contract',
  job_title: 'Job Title',

  // Finance
  tuition_fees: 'Tuition Fees',
  invoice: 'Invoice',
  payment: 'Payment',
  scholarship: 'Scholarship',
  discount: 'Discount',
  refund: 'Refund',
  budget: 'Budget',
  receipt: 'Receipt',

  // Library & Services
  library: 'Library',
  borrowing: 'Borrowing',
  housing_dormitory: 'Housing / Dormitory',
  certificate: 'Certificate',
  graduation_clearance: 'Graduation Clearance',

  // System / General
  dashboard: 'Dashboard',
  user: 'User',
  role: 'Role',
  permission: 'Permission',
  report: 'Report',
  notification: 'Notification',
  settings: 'Settings',
  login: 'Login',
  search: 'Search',
  save: 'Save',
  cancel: 'Cancel',
  delete: 'Delete',

  // Admin Dashboard
  admin_dashboard: 'University Administration Dashboard',
  system_active: 'System Active',
  overview_metrics: 'Overview of key metrics and recent activity across the university.',
  register_student: 'Register Student',
  admissions_queue: 'Admissions Queue',
  analytics: 'Analytics',
  total_enrollment: 'Total Enrolment',
  actively_enrolled: 'actively enrolled',
  academic_faculty: 'Academic Faculty',
  on_active_teaching: 'on active teaching',
  total_programs: 'Total Programs',
  active_courses: 'active courses',
  total_collected: 'Total Collected',
  collection_rate: 'collection rate',
  outstanding_fees: 'Outstanding Fees',
  pending_clearance: 'Pending student clearance',
  pending_admissions: 'Pending Admissions',
  total_applied: 'total applied',
  active_teaching: 'Active Teaching',
  total_sections: 'total sections',
  graduated_alumni: 'Graduated Alumni',
  issued_certs: 'issued certs',
  student_status_distribution: 'Student Status Distribution',
  total: 'Total',
  enrollment_lifecycle: 'Enrolment lifecycle breakdown across all departments',
  enrolled: 'Enrolled',
  pending: 'Pending',
  suspended: 'Suspended',
  graduated: 'Graduated',
  open_student_directory: 'Open Student Directory',
  tuition_fees_health: 'Tuition & Fees Health',
  collected: 'Collected',
  invoiced_totals: 'Invoiced totals against collected student payments',
  collection_progress: 'Collection Progress',
  total_invoiced: 'Total Invoiced',
  cleared_payments: 'Cleared Payments',
  outstanding_balance: 'Outstanding Balance',
  view_detailed_ledger: 'View Detailed Ledger',
  admissions_funnel: 'Admissions Funnel',
  candidates: 'Candidates',
  applicant_flow: 'New applicant flow and conversion to registered students',
  approved_offers: 'Approved Offers',
  enrolled_students: 'Enrolled Students',
  declined_rejected: 'Declined / Rejected',
  review_applications: 'Review Applications',
  academic_programs_enrollment: 'Academic Programs & Enrolment Density',
  leading_programs: 'Leading degree programs ranked by student volume',
  no_program_data: 'No program distribution data available.',
  active_cohort_progression: 'Active Cohort Progression',
  semester_breakdown: 'Students categorized by semester progression',
  no_semester_data: 'No semester cohort breakdown available.',
  students_count: 'Students',
  candidates_awaiting_review: 'Candidates awaiting review',
  view_all: 'View All',
  no_pending_admissions: 'No pending admissions at this moment.',
  review: 'Review',
  recent_receipts: 'Recent Receipts',
  incoming_payments: 'Incoming cashier & bank payments',
  ledger: 'Ledger',
  no_payment_transactions: 'No payment transactions recorded recently.',
  faculty_teaching: 'Faculty Teaching',
  active_schedules: 'Active course schedules & rooms',
  assignments: 'Assignments',
  no_teaching_assignments: 'No teaching assignments allocated.',
  administrative_management: 'Administrative Management Directory',
  quick_navigation: 'Quick navigation to core university management modules and configurations',
  students_directory: 'Student Directory',
  directory_profiles: 'Directory & Profiles',
  admissions_screen: 'Admissions',
  screen_admit: 'Screen & Admit',
  lecturers_staff: 'Lecturers',
  faculty_staff: 'Faculty Staff',
  courses_curriculum: 'Courses',
  curriculum_syllabus: 'Curriculum & Syllabus',
  finance_billing: 'Finance',
  billing_collections: 'Billing & Collections',
  hr_personnel: 'HR',
  personnel_payroll: 'Personnel & Payroll',
  reports_analytics: 'Analytics',
  analytics_insights: 'Analytics & Insights',
  settings_config: 'Settings',
  system_config: 'System Configuration',
  teaching_allocation: 'Teaching',
  course_allocation: 'Course Allocation',
  reports_institutional: 'Reports',
  institutional_data: 'Institutional Data',
  users_roles: 'Users & Roles',
  security_access: 'Security & Access',

  // Students Page
  students_management: 'Students Management',
  students_description: 'Manage and monitor all enrolled student records, academic performance, and fee status.',
  import_students: 'Import Students',
  create_student: 'Create Student',
  total_students: 'Total Students',
  active_enrolled: 'Active Enrolled',
  pending_enrollment: 'Pending Enrollment',
  suspended_status: 'Suspended',
  graduated_status: 'Graduated',
  students_list: 'Students List',
  search_students: 'Search by name, email, matric no, phone...',
  status: 'Status',
  fee_status: 'Fee Status',
  program: 'Program',
  semester_label: 'Semester',
  gender: 'Gender',
  all_statuses: 'All Statuses',
  enrolled_status: 'Enrolled',
  pending_status: 'Pending',
  suspended_label: 'Suspended',
  graduated_label: 'Graduated',
  withdrawn: 'Withdrawn',
  all_fees: 'All Fees',
  paid: 'Paid',
  unpaid: 'Unpaid',
  partial: 'Partial',
  all_programs: 'All Programs',
  all_semesters: 'All Semesters',
  all_genders: 'All Genders',
  male: 'Male',
  female: 'Female',
  delete_student_record: 'Delete Student Record',
  delete_student_description: 'Are you sure you want to delete this student? Their user account will be deactivated.',
  student_deleted_success: 'Student {matric_no} deleted successfully.',
  failed_delete_student: 'Failed to delete student.',
  student_account_activated: 'Student account activated.',
  student_account_suspended: 'Student account suspended.',
  failed_update_status: 'Failed to update student account status.',
  breadcrumb_students: 'Students',

  // Admissions Page
  admissions_management: 'Admissions Management',
  admissions_description: 'Review and process student admission applications, approve candidates, and convert to enrolled students.',
  applications_list: 'Applications List',
  search_applications: 'Search by name, email, application no...',
  create_application: 'Create Application',
  application_no: 'Application No',
  applicant_name: 'Applicant Name',
  program_applied: 'Program Applied',
  application_date: 'Application Date',
  application_status: 'Application Status',
  pending_application: 'Pending',
  approved_application: 'Approved',
  rejected_application: 'Rejected',
  admitted_application: 'Admitted',
  review_application: 'Review Application',
  convert_to_student: 'Convert to Student',
  application_approved: 'Application approved successfully.',
  application_rejected: 'Application rejected successfully.',
  under_review: 'Under Review',
  all_students: 'All Students',
  total_applications: 'Total Applications',
  enrolled_admissions: 'Enrolled Students',
  delete_application: 'Delete Application',
  delete_application_confirm: 'Are you sure you want to delete this application?',
  breadcrumb_admissions: 'Admissions',

  // Lecturers Page
  lecturers_management: 'Lecturers Management',
  lecturers_description: 'Manage faculty members, teaching assignments, and academic performance tracking.',
  lecturers_list: 'Lecturers List',
  lecturers_directory: 'Lecturers Directory',
  search_lecturers: 'Search by name, email, department...',
  create_lecturer: 'Create Lecturer',
  lecturer_name: 'Lecturer Name',
  lecturer_status: 'Status',
  active_lecturer: 'Active',
  inactive_lecturer: 'Inactive',
  courses_taught: 'Courses Taught',
  on_leave: 'On Leave',
  sabbatical: 'Sabbatical',
  terminated: 'Terminated',
  full_time: 'Full Time',
  part_time: 'Part Time',
  adjunct: 'Adjunct',
  visiting: 'Visiting',
  total_faculty: 'Total Faculty',
  registered_academic_staff: 'Registered Academic Staff',
  currently_lecturing: 'Currently Lecturing',
  sabbatical_leave: 'Sabbatical Leave',
  permanent_faculty: 'Permanent Faculty',
  part_time_adjunct: 'Part Time / Adjunct',
  visiting_adjunct_staff: 'Visiting Adjunct Staff',
  delete_lecturer: 'Delete Lecturer Record',
  delete_lecturer_confirm: 'Are you sure you want to delete this lecturer? Their user account will be deactivated.',
  lecturer_deleted: 'Lecturer {name} deleted successfully.',
  failed_delete_lecturer: 'Failed to delete lecturer record.',
  lecturer_status_updated: 'Lecturer status updated successfully.',
  failed_update_lecturer_status: 'Failed to update lecturer status.',
  reset_lecturer_password: 'Reset Lecturer Password',
  reset_password_description: 'Set a new secure password for this faculty member account.',
  breadcrumb_lecturers: 'Lecturers',

  // Assignments Page
  assignments_management: 'Teaching Assignments',
  assignments_description: 'Manage course assignments, teaching schedules, and room allocations.',
  assignments_list: 'Assignments List',
  search_assignments: 'Search by course code, lecturer name...',
  create_assignment: 'Create Assignment',
  course_code: 'Course Code',
  course_name: 'Course Name',
  assigned_lecturer: 'Assigned Lecturer',
  schedule: 'Schedule',
  room: 'Room',
  assignment_status: 'Status',
  active_assignment: 'Active',
  completed_assignment: 'Completed',
  all_years: 'All Years',
  all_lecturers: 'All Lecturers',
  all_courses: 'All Courses',
  assigned: 'Assigned',
  cancelled: 'Cancelled',
  total_assignments: 'Total Assignments',
  delete_assignment: 'Delete Assignment',
  delete_assignment_confirm: 'Are you sure you want to delete this assignment?',
  assignment_deleted: 'Assignment deleted successfully.',
  failed_delete_assignment: 'Failed to delete assignment.',
  semester_1: 'Semester 1',
  semester_2: 'Semester 2',
  semester_3: 'Semester 3',
  semester_4: 'Semester 4',
  semester_5: 'Semester 5',
  semester_6: 'Semester 6',
  breadcrumb_assignments: 'Assignments',

  // Programs Page
  programs_management: 'Academic Programs',
  programs_description: 'Manage degree programs, curriculum structure, and program requirements.',
  programs_list: 'Programs List',
  search_programs: 'Search by program name, code...',
  create_program: 'Create Program',
  program_name: 'Program Name',
  program_code: 'Program Code',
  program_level: 'Level',
  program_duration: 'Duration (years)',
  credit_requirements: 'Credit Requirements',
  code: 'Code',
  program_name_label: 'Program Name',
  degree_level: 'Degree Level',
  duration_semesters: 'Duration (Semesters)',
  total_credits: 'Total Credits',
  faculty_label: 'Faculty',
  program_status: 'Status',
  all_faculties: 'All Faculties',
  all_degree_levels: 'All Degree Levels',
  bachelor: 'Bachelor',
  master: 'Master',
  phd: 'PhD',
  diploma: 'Diploma',
  program_active: 'Active',
  program_inactive: 'Inactive',
  delete_program: 'Delete Program',
  delete_program_confirm: 'Are you sure you want to delete this program?',
  program_deleted: 'Program {name} deleted.',
  failed_delete_program: 'Failed to delete academic program.',
  total_programs_stats: 'Total Programs',
  active_programs_stats: 'Active Programs',
  total_students_stats: 'Total Students',
  total_courses_stats: 'Total Courses',
  faculties_count: 'Faculties Count',
  archived: 'Archived',
  actions: 'Actions',
  view: 'View',
  breadcrumb_programs: 'Programs',

  // Courses Page
  courses_management: 'Course Management',
  courses_description: 'Manage course catalog, prerequisites, and course materials.',
  courses_list: 'Courses List',
  search_courses: 'Search by course code, name...',
  create_course: 'Create Course',
  course_title: 'Course Title',
  course_credits: 'Credits',
  course_prerequisites: 'Prerequisites',
  breadcrumb_courses: 'Courses',

  // Semesters Page
  semesters_management: 'Academic Semesters',
  semesters_description: 'Manage academic calendar, semester schedules, and registration periods.',
  semesters_list: 'Semesters List',
  create_semester: 'Create Semester',
  semester_name: 'Semester Name',
  start_date: 'Start Date',
  end_date: 'End Date',
  registration_period: 'Registration Period',
  breadcrumb_semesters: 'Semesters',

  // Enrollments Page
  enrollments_management: 'Course Enrollments',
  enrollments_description: 'Manage student course registrations, add/drop requests, and enrollment status.',
  enrollments_list: 'Enrollments List',
  search_enrollments: 'Search by student, course...',
  create_enrollment: 'Create Enrollment',
  enrollment_student: 'Student',
  enrollment_course: 'Course',
  enrollment_semester: 'Semester',
  enrollment_status: 'Enrollment Status',
  breadcrumb_enrollments: 'Enrollments',

  // Transcripts Page
  transcripts_management: 'Academic Transcripts',
  transcripts_description: 'View and manage student academic records, grades, and transcript generation.',
  transcripts_list: 'Transcripts List',
  search_transcripts: 'Search by student name, matric no...',
  generate_transcript: 'Generate Transcript',
  student_record: 'Student Record',
  academic_performance: 'Academic Performance',
  transcript_generated: 'Transcript generated successfully.',
  breadcrumb_transcripts: 'Transcripts',

  // Finance Pages
  finance_management: 'Financial Management',
  finance_description: 'Manage tuition fees, invoices, payments, and financial reports.',
  finance_list: 'Finance List',
  search_finance: 'Search by invoice no, student...',
  create_invoice: 'Create Invoice',
  invoice_no: 'Invoice No',
  invoice_amount: 'Amount',
  invoice_due_date: 'Due Date',
  invoice_status: 'Status',
  payment_list: 'Payments List',
  search_payments: 'Search by transaction no, student...',
  record_payment: 'Record Payment',
  transaction_no: 'Transaction No',
  payment_amount: 'Amount',
  payment_method: 'Payment Method',
  payment_date: 'Payment Date',
  fees_management: 'Fees Management',
  fees_description: 'Manage fee structures, payment plans, and fee waivers.',
  breadcrumb_finance: 'Finance',
  breadcrumb_fees: 'Fees',
  breadcrumb_payments: 'Payments',
  breadcrumb_invoices: 'Invoices',

  // Expenses Page
  expenses_management: 'Expense Management',
  expenses_description: 'Track and manage university expenses, budgets, and cost allocations.',
  expenses_list: 'Expenses List',
  search_expenses: 'Search by expense type, date...',
  create_expense: 'Create Expense',
  expense_type: 'Expense Type',
  expense_category: 'Category',
  expense_amount: 'Amount',
  expense_date: 'Date',
  expense_description: 'Description',
  breadcrumb_expenses: 'Expenses',

  // Chart of Accounts Page
  chart_of_accounts: 'Chart of Accounts',
  chart_description: 'Manage financial accounts, account codes, and accounting structure.',
  accounts_list: 'Accounts List',
  search_accounts: 'Search by account code, name...',
  create_account: 'Create Account',
  account_code: 'Account Code',
  account_name: 'Account Name',
  account_type: 'Account Type',
  parent_account: 'Parent Account',
  breadcrumb_chart_of_accounts: 'Chart of Accounts',

  // Reports Page
  reports_management: 'Reports',
  reports_description: 'View and generate various reports for academic, financial, and administrative analysis.',
  reports_list: 'Reports List',
  generate_report: 'Generate Report',
  report_type: 'Report Type',
  date_range: 'Date Range',
  export_report: 'Export Report',
  breadcrumb_reports: 'Reports',

  // Settings - System
  system_settings: 'System Settings',
  system_settings_description: 'Configure system-wide settings, preferences, and application configuration.',
  application_name: 'Application Name',
  timezone: 'Timezone',
  date_format: 'Date Format',
  time_format: 'Time Format',
  language: 'Language',
  maintenance_mode: 'Maintenance Mode',
  save_settings: 'Save Settings',
  breadcrumb_system_settings: 'System Settings',

  // Settings - Roles
  roles_management: 'Roles & Permissions',
  roles_description: 'Manage user roles, permissions, and access control.',
  roles_list: 'Roles List',
  create_role: 'Create Role',
  role_name: 'Role Name',
  permissions: 'Permissions',
  assign_permissions: 'Assign Permissions',
  delete_role: 'Delete Role',
  delete_role_confirm: 'Are you sure you want to delete this role?',
  breadcrumb_roles: 'Roles',

  // Settings - Audit Log
  audit_log: 'Audit Log',
  audit_log_description: 'View system activity logs, user actions, and security events.',
  audit_logs_list: 'Audit Logs',
  filter_logs: 'Filter Logs',
  user_action: 'User Action',
  event_type: 'Event Type',
  ip_address: 'IP Address',
  timestamp: 'Timestamp',
  breadcrumb_audit_log: 'Audit Log',

  // Settings - Users
  users_management: 'Users Management',
  users_description: 'Manage system users, accounts, and user access.',
  users_list: 'Users List',
  create_user: 'Create User',
  user_name: 'User Name',
  user_email: 'User Email',
  user_role: 'User Role',
  user_status: 'User Status',
  deactivate_user: 'Deactivate User',
  activate_user: 'Activate User',
  reset_password: 'Reset Password',
  delete_user: 'Delete User',
  delete_user_confirm: 'Are you sure you want to delete this user?',
  breadcrumb_users: 'Users',

  // Reports Page Metrics
  program_distribution: 'Program Distribution',
  admission_pipeline: 'Admissions Pipeline',
  lecturer_assignments_reports: 'Lecturer Assignments',
  cohort_progression: 'Cohort Progression by Semester',
  recent_payments_reports: 'Recent Payments',
  top_performers: 'Top Academic Performers',
  program_leadership: 'Program Leadership',
  student_academic_progression: 'Student Academic Progression',
  student_academic_progression_description: 'Track student retention and progression across semesters.',
  no_cohort_data: 'No cohort progression data available.',
  total_certificates_issued: 'Total Certificates Issued',

  // System Settings Page
  system_configuration_saved: 'System configuration saved successfully.',
  total_accounts: 'Total Accounts',
  enrolled_students_system: 'Enrolled Students',
  total_programs_system: 'Total Programs',
  total_courses_system: 'Total Courses',
  total_lecturers_system: 'Total Lecturers',
  active_assignments_system: 'Active Assignments',
  php_version: 'PHP Version',
  laravel_version: 'Laravel Version',
  server_software: 'Server Software',
  database_driver: 'Database Driver',
  database_name: 'Database Name',
  cache_driver: 'Cache Driver',
  queue_driver: 'Queue Driver',
  timezone_system: 'Timezone',
  environment: 'Environment',
  debug_mode: 'Debug Mode',
  system_configuration_diagnostics: 'System Configuration & Server Diagnostics',
  system_institutional_configurations: 'System & Institutional Configurations',
  system_config_description: 'Manage institution metadata, portal enrollment locks, academic session dates, and server environment health.',
  saving_changes: 'Saving...',
  save_changes: 'Save Changes',
  institution_name: 'Institution Name',
  institution_motto: 'Institution Motto',
  contact_email: 'Contact Email',
  contact_phone: 'Contact Phone',
  campus_address: 'Campus Address',
  academic_year: 'Academic Year',
  current_term: 'Current Term',
  student_registration_enabled: 'Student Registration Enabled',
  course_enrollment_open: 'Course Enrollment Open',
  maintenance_mode_system: 'Maintenance Mode',
  late_fee_percentage: 'Late Fee Percentage',

  // Courses Page
  course_deleted: 'Course {code} - {name} deleted.',
  failed_delete_course: 'Failed to delete course.',
  general_program: 'General Program',
  lecturer_assignments_label: 'Lecturer Assignments',
  all_semesters_filter: 'All Semesters',
  all_levels_filter: 'All Levels',
  all_programs_filter: 'All Programs',
  semester_prefix: 'Sem',
  delete_course: 'Delete Course',
  delete_course_confirm: 'Are you sure you want to delete this course?',
  active_courses_stats: 'Active Courses',
  total_assignments_stats: 'Total Assignments',
  total_credits_stats: 'Total Credits',

  // Semesters Page
  semester_curricula_cohorts: 'Semester Curricula & Cohorts',
  semester_overview_cohort: 'Semester Overview & Cohort Distribution',
  semester_description: 'View semester-wise curriculum distribution, cohort sizes, and course allocations across all academic programs.',
  total_semesters_stats: 'Total Semesters',
  active_cohorts_stats: 'Active Cohorts',
  total_courses_offered_stats: 'Total Courses Offered',
  total_enrolled_students_stats: 'Total Enrolled Students',
  filter_by_program: 'Filter by Program',
  all_programs_semesters: 'All Programs',
  semester_label_page: 'Semester',
  level_label: 'Level',
  courses_count_label: 'Courses',
  students_count_label: 'Students',
  total_credits_label: 'Total Credits',
  view_courses: 'View Courses',
  active_status: 'Active',
  program_semesters: 'Program Semesters',
  workload: 'Workload',
  curriculum_courses: 'Curriculum Courses',
  no_courses_configured: 'No courses configured yet.',

  // Enrollments Page
  total_enrolled_stats: 'Total Enrolled',
  active_students_enrollments: 'Active Students',
  pending_enrollments_stats: 'Pending Enrollments',
  graduated_students_enrollments: 'Graduated Students',
  suspended_students_enrollments: 'Suspended Students',
  matric_number: 'Matric No',
  enrollment_status_page: 'Enrollment Status',
  current_semester_enrollment: 'Current Semester',
  fee_status_enrollment: 'Fee Status',
  enrollment_date_label: 'Enrollment Date',
  gpa_label_enrollment: 'GPA',
  enrollment_active: 'Active',
  enrollment_pending: 'Pending',
  enrollment_graduated: 'Graduated',
  enrollment_suspended: 'Suspended',
  enrolled_status_enrollment: 'Enrolled',
  pending_fee_status: 'Pending',
  paid_fee_status: 'Paid',
  partial_fee_status: 'Partial',
  view_enrollment: 'View Enrollment',
  unassigned: 'Unassigned',
  term: 'Term',
  enroll_student: 'Enroll Student',
  enrollment_roster: 'Enrollment Roster',

  // Transcripts Page
  total_students_transcripts: 'Total Students',
  avg_institution_gpa: 'Avg Institution GPA',
  total_grades_recorded: 'Total Grades Recorded',
  certificates_issued: 'Certificates Issued',
  grades_count_label: 'Grades',
  certificates_count_label: 'Certificates',
  transcript_student_name: 'Student Name',
  transcript_program: 'Program',
  transcript_term: 'Term',
  transcript_gpa: 'GPA',
  view_transcript: 'View Transcript',
  generate_transcript_button: 'Generate Transcript',
  cumulative_gpa: 'Cumulative GPA',
  issued: 'issued',

  // Finance Overview Page
  financial_solvency_revenue: 'Financial Solvency & Revenue Overview',
  finance_bursar_center: 'Finance & Bursar Control Center',
  finance_description: 'Real-time tuition fee assessment, fee collections, student payment verification, and cashflow audit.',
  total_invoiced_finance: 'Total Invoiced',
  total_collected_finance: 'Total Collected',
  total_outstanding_finance: 'Total Outstanding',
  pending_payments_finance: 'Pending Payments',
  overdue_invoices_finance: 'Overdue Invoices',
  recent_transactions: 'Recent Transactions',
  recent_invoices_finance: 'Recent Invoices',
  revenue_by_payment_method: 'Revenue by Payment Method',
  invoices_by_type: 'Invoices by Type',
  transaction_no_label: 'Transaction No',
  payment_date_label: 'Payment Date',
  invoice_no_label: 'Invoice No',
  invoice_title: 'Title',
  invoice_type: 'Type',
  paid_amount: 'Paid Amount',
  due_date_label: 'Due Date',
  view_all_payments: 'View All Payments',
  view_all_invoices: 'View All Invoices',
  manage_fees: 'Manage Fees',
  chart_of_accounts_label: 'Chart of Accounts',
  no_payment_transactions: 'No payment transactions recorded yet.',
  no_invoices_recorded: 'No invoices recorded yet.',
  recent_invoices_desc: 'Latest tuition and fee invoices issued to students.',

  // Fees Page
  fee_schedules: 'Fee Schedules',
  fee_schedules_description: 'Manage student fee structures, payment plans, and fee assessments.',
  total_students_fees: 'Total Students',
  fully_paid_students: 'Fully Paid',
  partial_students: 'Partial',
  unpaid_students: 'Unpaid',
  total_receivables: 'Total Receivables',
  matric_no_fees: 'Matric No',
  total_billed: 'Total Billed',
  total_paid_fees: 'Total Paid',
  balance: 'Balance',
  fee_status_filter: 'Fee Status',
  all_fee_statuses: 'All Fee Statuses',
  fully_paid_status: 'Fully Paid',
  partial_status: 'Partial',
  unpaid_status: 'Unpaid',
  program_filter_fees: 'Program',
  all_programs_fees: 'All Programs',
  view_student_profile: 'View Profile',
  institutional_tuition_schedule: 'Institutional Tuition Schedule (Standard Academic Year 2026/2027)',
  fees_list_label: 'Student Fee Directory',
  search_fees: 'Search by matric no, student name...',
  approved_fee_schedule: 'Approved standard fee schedule by faculty degree program.',
  undergraduate_tuition: 'Undergraduate Tuition',
  postgraduate_tuition: 'Postgraduate Tuition',
  one_time_institutional_fees: 'One-Time Institutional Fees',
  includes_registration: 'Includes course registration, lab access, campus library, and examination fees.',
  includes_thesis: 'Includes advanced thesis supervision, journal repository, and laboratory facilities.',
  admission_matriculation: 'Admission & Matriculation',
  graduation_transcript: 'Graduation & Transcript',
  bachelor: 'Bachelor',
  master: 'Master',
  phd: 'Ph.D.',

  // Payments Page
  payments_roster: 'Payments Roster',
  payments_description: 'Track and manage all student payment transactions, payment methods, and reconciliation.',
  payments_list: 'Payments List',
  search_payments: 'Search by transaction no, student name...',
  transaction_no_payments: 'Transaction No',
  payment_amount_payments: 'Amount',
  payment_method_payments: 'Payment Method',
  payment_date_payments: 'Payment Date',
  student_name_payments: 'Student Name',
  program_payments: 'Program',
  status_payments: 'Status',
  all_statuses_payments: 'All Statuses',
  completed_payment: 'Completed',
  pending_payment: 'Pending',
  failed_payment: 'Failed',
  refunded_payment: 'Refunded',
  record_payment: 'Record Payment',
  payment_method_filter: 'Payment Method',
  all_payment_methods: 'All Methods',
  total_collected: 'Total Collected',
  todays_collections: "Today's Collections",
  total_transactions: 'Total Transactions',
  approve: 'Approve',
  reject: 'Reject',
  enter_payment_details: 'Enter payment transaction details received from student.',
  select_student: 'Select Student',
  receipt_reference_note: 'Receipt / Reference Note',
  saving: 'Saving...',
  no_due_date: 'No Due Date',
  overdue: 'Overdue',
  paid_invoice: 'Paid',
  partial_paid_invoice: 'Partial',
  items: 'Items',
  view: 'View',
  total_invoiced: 'Total Invoiced',
  total_paid: 'Total Paid',
  outstanding_due: 'Outstanding Due',
  issue_invoice: 'Issue Invoice',
  total_invoices: 'Total Invoices',
  overdue_invoices: 'Overdue Invoices',
  bills: 'bills',
  issue_student_invoice: 'Issue Student Invoice',
  create_invoice_description: 'Create an official invoice bill assigned to student fee ledger.',
  invoice_title: 'Invoice Title',
  fee_category: 'Fee Category',
  line_items: 'Line Items',
  add_item: 'Add Item',
  add_line_items_description: 'Add line items to itemize the invoice charges.',
  computed_amount: 'Computed amount',
  delete_invoice: 'Delete Invoice',
  delete_invoice_description: 'Are you sure you want to delete this invoice? Invoices with collected payments cannot be deleted.',

  // Invoices Page
  invoices_list_page: 'Invoices',
  invoices_description: 'Manage student tuition invoices, fee assessments, and billing records.',
  invoices_list_label: 'Invoices List',
  search_invoices: 'Search by invoice no, student name...',
  invoice_no_invoices: 'Invoice No',
  invoice_title_invoices: 'Title',
  invoice_type_invoices: 'Type',
  invoice_amount_invoices: 'Amount',
  due_date_invoices: 'Due Date',
  paid_amount_invoices: 'Paid Amount',
  balance_invoices: 'Balance',
  status_invoices: 'Status',
  all_statuses_invoices: 'All Statuses',
  draft_invoice: 'Draft',
  sent_invoice: 'Sent',
  partial_paid_invoice: 'Partial Paid',
  paid_invoice: 'Paid',
  overdue_invoice: 'Overdue',
  cancelled_invoice: 'Cancelled',
  create_invoice: 'Create Invoice',
  invoice_type_filter: 'Invoice Type',
  all_invoice_types: 'All Types',

  // Expenses Page
  expenses_management_page: 'Expense Management',
  expenses_description_page: 'Track and manage university expenses, budgets, and cost allocations.',
  expenses_list_page: 'Expenses List',
  search_expenses_page: 'Search by expense type, date...',
  create_expense_page: 'Create Expense',
  expense_type_page: 'Expense Type',
  expense_category_page: 'Category',
  expense_amount_page: 'Amount',
  expense_date_page: 'Date',
  expense_description_page: 'Description',
  all_expense_types: 'All Types',
  all_categories: 'All Categories',

  // Chart of Accounts Page
  chart_of_accounts_page: 'Chart of Accounts',
  chart_description_page: 'Manage financial accounts, account codes, and accounting structure.',
  accounts_list_page: 'Accounts List',
  search_accounts_page: 'Search by account code, name...',
  create_account_page: 'Create Account',
  account_code_page: 'Account Code',
  account_name_page: 'Account Name',
  account_type_page: 'Account Type',
  parent_account_page: 'Parent Account',
  all_account_types: 'All Types',
  asset: 'Asset',
  liability: 'Liability',
  equity: 'Equity',
  revenue: 'Revenue',
  expense: 'Expense',

  // Expenses Page - Detailed
  university_expense_management: 'University Expense Management',
  university_expense_description: 'Track operational and academic expenses against the UCT chart of accounts with multi-level approval.',
  finance_overview: 'Finance Overview',
  record_expense: 'Record Expense',
  total_expense: 'Total Expense',
  pending_approval_expenses: 'Pending Approval',
  this_month_expenses: 'This Month',
  total_vouchers: 'Total Vouchers',
  rejected_expenses: 'Rejected',
  expense_vouchers: 'Expense Vouchers',
  search_expenses_description: 'Search by expense no, title, vendor, budget line, or account...',
  expense_no_column: 'Expense No',
  expense_column: 'Expense',
  account_column: 'Account',
  amount_column: 'Amount',
  date_column: 'Date',
  budget_line_column: 'Budget Line',
  status_column: 'Status',
  actions_column: 'Actions',
  mark_paid: 'Mark Paid',
  approve_expense: 'Approve',
  reject_expense: 'Reject',
  view_expense: 'View',
  all_statuses_filter: 'All Statuses',
  draft_status: 'Draft',
  pending_approval_status: 'Pending Approval',
  approved_status: 'Approved',
  paid_status: 'Paid',
  rejected_status: 'Rejected',
  cancelled_status: 'Cancelled',
  all_accounts_filter: 'All Accounts',
  record_university_expense: 'Record University Expense',
  record_expense_description: 'Submit an expense voucher. Submitted expenses enter the multi-level approval chain.',
  expense_title: 'Expense Title',
  expense_title_placeholder: 'e.g. Electricity bill for main campus',
  account_select: 'Account',
  select_account: 'Select account...',
  amount_dollar: 'Amount ($)',
  amount_placeholder: '1500.00',
  expense_date_label: 'Expense Date',
  pick_date: 'Pick a date',
  vendor_payee: 'Vendor / Payee',
  vendor_placeholder: 'e.g. Golis Electric',
  budget_line_label: 'Budget Line',
  budget_line_placeholder: 'e.g. Operations',
  expense_status_label: 'Status',
  submit_for_approval: 'Submit for Approval',
  save_as_draft: 'Save as Draft',
  description_label: 'Description',
  description_placeholder: 'Details about this expense...',
  notes_label: 'Notes',
  record_expense_button: 'Record Expense',
  saving: 'Saving...',
  reject_expense_title: 'Reject Expense',
  reject_expense_description: 'Provide a reason for rejecting {expense_no}. Rejection requires a comment.',
  rejection_reason: 'Rejection Reason',
  rejection_reason_placeholder: 'Explain why this expense is being rejected...',
  confirm_reject: 'Reject',
  expense_deleted: 'Expense {expense_no} deleted.',
  failed_delete_expense: 'Failed to delete expense.',
  expense_approved: 'Expense {expense_no} approved.',
  approval_failed: 'Approval failed.',
  expense_marked_paid: 'Expense {expense_no} marked as paid.',
  failed_mark_paid: 'Failed to mark expense as paid.',
  expense_rejected: 'Expense {expense_no} rejected.',
  failed_reject_expense: 'Failed to reject expense.',
  breadcrumb_dashboard: 'Dashboard',
  breadcrumb_finance: 'Finance',
  breadcrumb_expenses: 'Expenses',

  // Chart of Accounts Page - Detailed
  dashboard_breadcrumb: 'Dashboard',
  finance_breadcrumb: 'Finance',
  chart_of_accounts_breadcrumb: 'Chart of Accounts',
  total_accounts_coa: 'Total Accounts',
  active_accounts_coa: 'Active Accounts',
  inactive_accounts_coa: 'Inactive Accounts',
  account_groups_coa: 'Account Groups',
  configured_accounts_roster: 'Configured Accounts Roster',
  search_accounts_description: 'Search by account code, name, type, status...',
  account_name_column: 'Account Name',
  account_type_column: 'Type',
  normal_balance_column: 'Normal Balance',
  account_status_column: 'Status',
  transactions_column: 'Transactions',
  account_actions_column: 'Actions',
  debit_balance: 'Debit',
  credit_balance: 'Credit',
  active_status_coa: 'Active',
  inactive_status_coa: 'Inactive',
  add_account: 'Add Account',
  add_account_description: 'Create a new account in the UCT chart of accounts.',
  account_group: 'Account Group',
  select_account_group: 'Select account group...',
  account_code_label: 'Account Code',
  account_code_placeholder: 'e.g. 4030',
  suggested_code: 'Suggested code',
  available: 'Available',
  account_codes_are_4_digit: 'Account codes are 4-digit numbers.',
  code_already_in_use: 'This account code is already in use.',
  available_within_range: 'Available — within {group} ({range})',
  account_name_label_coa: 'Account Name',
  account_name_placeholder: 'e.g. Tuition Revenue — New Program',
  account_type_label_coa: 'Account Type',
  normal_balance_label_coa: 'Normal Balance',
  auto_derived_from_group: 'Auto-derived from group',
  description_label_coa: 'Description',
  description_placeholder_coa: 'Optional details about this account...',
  status_label_coa: 'Status',
  cancel_button: 'Cancel',
  create_account_button: 'Create Account',
  account_created_success: 'Account created successfully.',
  unable_create_account: 'Unable to create the account. Review the errors below.',
  edit_account: 'Edit Account',
  account_has_transactions: 'This account has posted transactions, so its account code and group cannot be changed.',
  code_locks_transactions: 'Code locks once the account has posted transactions.',
  account_updated_success: 'Account updated successfully.',
  unable_update_account: 'Unable to update the account. Review the errors below.',
  save_changes_button: 'Save Changes',
  account_details: 'Account Details',
  account_information: 'Account Information',
  account_code_info: 'Account Code',
  account_group_info: 'Account Group',
  type_info: 'Type',
  normal_balance_info: 'Normal Balance',
  code_range_info: 'Code Range',
  status_info: 'Status',
  description_info: 'Description',
  no_description_provided: 'No description provided.',
  created_info: 'Created',
  last_updated: 'Last Updated',
  financial_activity: 'Financial Activity',
  total_credits: 'Total Credits',
  total_debits: 'Total Debits',
  transactions_info: 'Transactions',
  posted: 'posted',
  recent_transactions: 'Recent Transactions',
  account_history: 'Account History',
  action_history: 'Action',
  changes_history: 'Changes',
  actor_history: 'Actor',
  timestamp_history: 'Timestamp',
  system_badge: 'System',
  view_transactions: 'View Transactions',
  toggle_status: 'Toggle Status',
  delete_account: 'Delete Account',
  account_type_asset: 'Asset',
  account_type_liability: 'Liability',
  account_type_equity: 'Equity',
  account_type_revenue: 'Revenue',
  account_type_expense: 'Expense',
  filter_by_group: 'Group',
  filter_by_type: 'Type',
  filter_by_balance: 'Normal Balance',
  filter_by_status_coa: 'Status',
  all_groups: 'All Groups',
  all_types_coa: 'All Types',
  all_balances: 'All Balances',
  all_statuses_coa: 'All Statuses',
  assets: 'Assets',
  liabilities: 'Liabilities',
  equity: 'Equity',
  revenue: 'Revenue',
  expenses_direct_academic: 'Expenses (Direct Academic)',
  expenses_operating: 'Expenses (Operating)',
  finance_costs_other: 'Finance Costs & Other',

  // Users Page - Detailed
  user_management_access_control: 'User Management & Access Control',
  user_management_description: 'Provision system logins, assign institutional roles, activate/deactivate credentials, and reset security passkeys.',
  roles_permissions: 'Roles & Permissions',
  create_user_button: 'Create User',
  total_users_stats: 'Total Users',
  active_accounts_stats: 'Active Accounts',
  super_admins_stats: 'Super Admins',
  faculty_lecturers_stats: 'Faculty Lecturers',
  enrolled_students_stats: 'Enrolled Students',
  system_accounts_roster: 'System Accounts Roster',
  search_users_description: 'Search by name, email...',
  user_account_column: 'User Account',
  assigned_role_column: 'Assigned Role',
  account_status_column: 'Account Status',
  created_on_column: 'Created On',
  password_button: 'Password',
  edit_button: 'Edit',
  delete_button: 'Delete',
  role_filter: 'Role',
  all_roles_filter: 'All Roles',
  super_admin_role: 'Super Admin',
  registrar_role: 'Registrar',
  finance_role: 'Finance',
  hr_role: 'HR',
  lecturer_role: 'Lecturer',
  student_role: 'Student',
  status_filter_users: 'Status',
  all_statuses_users: 'All Statuses',
  active_status_users: 'Active',
  deactivated_status: 'Deactivated',
  provision_new_user: 'Provision New User',
  provision_user_description: 'Create an authenticated institutional account.',
  full_name: 'Full Name',
  full_name_placeholder: 'e.g. Dr. Ahmed Hassan',
  user_email_label: 'Email',
  email_placeholder: 'e.g. ahmed.hassan@uct.edu',
  password_label: 'Password',
  password_placeholder: 'Enter secure password',
  user_role_label: 'Role',
  select_role: 'Select role...',
  account_active: 'Account Active',
  create_user_button_modal: 'Create User',
  user_created_success: 'User created successfully.',
  failed_create_user: 'Failed to create user.',
  edit_user: 'Edit User',
  edit_user_description: 'Update user information and access settings.',
  update_user: 'Update User',
  user_updated_success: 'User updated successfully.',
  failed_update_user: 'Failed to update user.',
  reset_password_title: 'Reset Password',
  reset_password_description: 'Set a new secure password for this user account.',
  new_password: 'New Password',
  confirm_password: 'Confirm Password',
  reset_password_button: 'Reset Password',
  password_reset_success: 'Password reset successfully.',
  failed_reset_password: 'Failed to reset password.',
  delete_user_title: 'Delete User',
  delete_user_description: 'Are you sure you want to delete this user? This action cannot be undone.',
  user_deleted_success: 'User deleted successfully.',
  failed_delete_user: 'Failed to delete user.',
  user_status_updated: 'User status updated.',
  failed_update_user_status: 'Failed to update user status.',
  breadcrumb_settings: 'Settings',
  breadcrumb_system: 'System',
  breadcrumb_users: 'User Management',

  // Roles Page - Detailed
  roles_permissions_management: 'Roles & Access Permissions',
  roles_permissions_description: 'Manage role hierarchies, configure fine-grained module privileges, and audit assigned user accounts.',
  users_roster: 'Users Roster',
  create_role_button: 'Create Role',
  total_roles_stats: 'Total Roles',
  system_core_roles: 'System Core Roles',
  custom_roles_stats: 'Custom Roles',
  defined_privileges: 'Defined Privileges',
  assigned_users_stats: 'Assigned Users',
  configured_roles_roster: 'Configured Roles Roster',
  search_roles_description: 'Search by role name, slug, description...',
  role_name_column: 'Role Name',
  description_column: 'Description',
  permissions_column: 'Permissions',
  assigned_users_column: 'Assigned Users',
  no_description_provided_role: 'No description provided.',
  privileges_count: 'Privileges',
  accounts_count: 'accounts',
  view_role: 'View',
  edit_role: 'Edit',
  delete_role_button: 'Delete',
  delete_custom_role: 'Delete Custom Role',
  delete_role_description: 'Are you sure you want to delete this custom role? This will revoke all permissions attached to it.',
  role_deleted_success: 'Role {name} deleted.',
  failed_delete_role: 'Failed to delete role.',
  breadcrumb_roles_page: 'Roles & Permissions',

  // Audit Log Page - Detailed
  security_audit_trail_log: 'Security & Audit Trail Log',
  audit_log_description: 'Comprehensive ledger of all administrative events, user authentications, financial actions, and record modifications.',
  users_roster_link: 'Users Roster',
  total_logged_events: 'Total Logged Events',
  events_today: 'Events Today',
  security_events: 'Security Events',
  active_sessions: 'Active Sessions',
  security_audit_records: 'Security Audit Records',
  search_audit_description: 'Search by initiator, resource, IP address...',
  initiator_column: 'Initiator',
  event_action_column: 'Event Action',
  target_entity_column: 'Target Entity / Resource',
  network_device_column: 'Network & Device',
  status_column_audit: 'Status',
  timestamp_column_audit: 'Timestamp',
  event_category_filter: 'Event Category',
  all_events_filter: 'All Events',
  settings_updated: 'Settings Updated',
  payment_verified: 'Payment Verified',
  course_created: 'Course Created',
  admission_approved: 'Admission Approved',
  grade_submitted: 'Grade Submitted',
  invoice_issued: 'Invoice Issued',
  user_created_audit: 'User Created',
  completed_status_audit: 'Completed',
  pending_status_audit: 'Pending',
  failed_status_audit: 'Failed',
  breadcrumb_audit_log_page: 'Audit Log',

  // Settings Pages
  settings_page: 'Settings',
  settings_description: 'Manage your profile and account settings',
  profile_settings: 'Profile',
  profile_settings_description: 'Update your name and email address',
  security_settings: 'Security',
  appearance_settings: 'Appearance',
  appearance_settings_description: 'Update the appearance settings for your account',
  language_settings: 'Language',
  language_settings_description: 'Select your preferred language for the interface',
  name_label: 'Name',
  full_name_placeholder: 'Full name',
  email_address_label: 'Email address',
  email_address_placeholder: 'Email address',
  save_button: 'Save',
  update_profile_button: 'Update Profile',
  email_unverified: 'Your email address is unverified.',
  resend_verification_email: 'Click here to re-send the verification email.',
  verification_link_sent: 'A new verification link has been sent to your email address.',
  current_password_label: 'Current password',
  current_password_placeholder: 'Current password',
  new_password_label: 'New password',
  new_password_placeholder: 'New password',
  confirm_password_label: 'Confirm password',
  confirm_password_placeholder: 'Confirm password',
  update_password_button: 'Update Password',
  security_description: 'Ensure your account is using a long, random password to stay secure',
  select_language: 'Select Language',
  english_language: 'English',
  arabic_language: 'Arabic',
  language_saved: 'Language preference saved successfully.',
  profile_updated: 'Profile updated successfully.',
  password_updated: 'Password updated successfully.',
  settings_breadcrumb: 'Settings',
  profile_breadcrumb: 'Profile',
  security_breadcrumb: 'Security',
  appearance_breadcrumb: 'Appearance',
  language_breadcrumb: 'Language',
  update_password_label: 'Update password',
  settings_menu: 'Settings',
  profile_menu: 'Profile',
  security_menu: 'Security',
  appearance_menu: 'Appearance',
  language_menu: 'Language',

  // Navigation
  nav_platform: 'Platform',
  nav_admin_portal: 'Admin Portal',
  nav_lecturer_portal: 'Lecturer Portal',
  nav_student_portal: 'Student Portal',
  nav_finance_portal: 'Finance Portal',
  nav_dashboard: 'Dashboard',
  nav_students: 'Students',
  nav_admissions: 'Admissions',
  nav_lecturers: 'Lecturers',
  nav_assignments: 'Assignments',
  nav_academic: 'Academic',
  nav_programs: 'Programs',
  nav_courses: 'Courses',
  nav_semesters: 'Semesters',
  nav_enrollments: 'Enrollments',
  nav_transcripts: 'Transcripts',
  nav_finance: 'Finance',
  nav_finance_overview: 'Overview',
  nav_fees: 'Fees',
  nav_payments: 'Payments',
  nav_invoices: 'Invoices',
  nav_expenses: 'Expenses',
  nav_chart_of_accounts: 'Chart of Accounts',
  nav_reports: 'Reports',
  nav_settings: 'Settings',
  nav_general_settings: 'General Settings',
  nav_user_management: 'User Management',
  nav_roles_permissions: 'Roles & Permissions',
  nav_audit_log: 'Audit Log',
  nav_finance_expenses: 'Expenses',
  nav_all_expenses: 'All Expenses',
  nav_approvals: 'Approvals',
  nav_my_courses: 'My Courses',
  nav_attendance: 'Attendance',
  nav_gradebook: 'Gradebook',
  nav_materials: 'Materials',
  nav_grades: 'Grades',
  nav_documents: 'Documents',
  nav_certificates: 'Certificates',

  // User Menu
  menu_settings: 'Settings',
  menu_logout: 'Log out',
};

export default en;
