const en = {
  // Admissions & Students
  admission: 'Admission',
  applicant: 'Applicant',
  student: 'Student',
  student_id: 'Student ID',
  enrollment: 'Enrollment',
  transfer: 'Transfer',
  withdrawal: 'Withdrawal',
  graduate: 'Graduate',

  // Academic Structure
  faculty_college: 'Faculty / College',
  department: 'Department',
  program_major: 'Program / Major',
  course: 'Course',
  credit_hours: 'Credit Hours',
  semester: 'Semester',
  academic_year: 'Academic Year',
  prerequisite: 'Prerequisite',
  syllabus: 'Syllabus',
  study_plan: 'Study Plan',

  // Registration & Timetable
  course_registration: 'Course Registration',
  add_drop: 'Add/Drop',
  section: 'Section',
  timetable: 'Timetable',
  lecture_hall: 'Lecture Hall',
  attendance: 'Attendance',
  absence: 'Absence',
  academic_advisor: 'Academic Advisor',

  // Exams & Grades
  exam: 'Exam',
  midterm: 'Midterm',
  final_exam: 'Final Exam',
  grade: 'Grade',
  gpa: 'GPA',
  semester_gpa: 'Semester GPA',
  transcript: 'Transcript',
  academic_probation: 'Academic Probation',
  incomplete: 'Incomplete',
  result: 'Result',

  // Faculty & HR
  instructor_lecturer: 'Instructor / Lecturer',
  professor: 'Professor',
  teaching_assistant: 'Teaching Assistant',
  employee: 'Employee',
  payroll: 'Payroll',
  leave: 'Leave',
  contract: 'Contract',
  job_title: 'Job Title',

  // Finance
  tuition_fees: 'Tuition Fees',
  invoice: 'Invoice',
  payment: 'Payment',
  scholarship: 'Scholarship',
  discount: 'Discount',
  refund: 'Refund',
  budget: 'Budget',
  receipt: 'Receipt',

  // Library & Services
  library: 'Library',
  borrowing: 'Borrowing',
  housing_dormitory: 'Housing / Dormitory',
  certificate: 'Certificate',
  graduation_clearance: 'Graduation Clearance',

  // System / General
  dashboard: 'Dashboard',
  user: 'User',
  role: 'Role',
  permission: 'Permission',
  report: 'Report',
  notification: 'Notification',
  settings: 'Settings',
  login: 'Login',
  search: 'Search',
  save: 'Save',
  cancel: 'Cancel',
  delete: 'Delete',

  // Admin Dashboard
  admin_dashboard: 'University Administration Dashboard',
  system_active: 'System Active',
  overview_metrics: 'Overview of key metrics and recent activity across the university.',
  register_student: 'Register Student',
  admissions_queue: 'Admissions Queue',
  analytics: 'Analytics',
  total_enrollment: 'Total Enrolment',
  actively_enrolled: 'actively enrolled',
  academic_faculty: 'Academic Faculty',
  on_active_teaching: 'on active teaching',
  total_programs: 'Total Programs',
  active_courses: 'active courses',
  total_collected: 'Total Collected',
  collection_rate: 'collection rate',
  outstanding_fees: 'Outstanding Fees',
  pending_clearance: 'Pending student clearance',
  pending_admissions: 'Pending Admissions',
  total_applied: 'total applied',
  active_teaching: 'Active Teaching',
  total_sections: 'total sections',
  graduated_alumni: 'Graduated Alumni',
  issued_certs: 'issued certs',
  student_status_distribution: 'Student Status Distribution',
  total: 'Total',
  enrollment_lifecycle: 'Enrolment lifecycle breakdown across all departments',
  enrolled: 'Enrolled',
  pending: 'Pending',
  suspended: 'Suspended',
  graduated: 'Graduated',
  open_student_directory: 'Open Student Directory',
  tuition_fees_health: 'Tuition & Fees Health',
  collected: 'Collected',
  invoiced_totals: 'Invoiced totals against collected student payments',
  collection_progress: 'Collection Progress',
  total_invoiced: 'Total Invoiced',
  cleared_payments: 'Cleared Payments',
  outstanding_balance: 'Outstanding Balance',
  view_detailed_ledger: 'View Detailed Ledger',
  admissions_funnel: 'Admissions Funnel',
  candidates: 'Candidates',
  applicant_flow: 'New applicant flow and conversion to registered students',
  pending_review: 'Pending Review',
  approved_offers: 'Approved Offers',
  enrolled_students: 'Enrolled Students',
  declined_rejected: 'Declined / Rejected',
  review_applications: 'Review Applications',
  academic_programs_enrollment: 'Academic Programs & Enrolment Density',
  leading_programs: 'Leading degree programs ranked by student volume',
  no_program_data: 'No program distribution data available.',
  enrolled_students_count: 'Enrolled Students',
  offered_courses: 'Offered Courses',
  active_cohort_progression: 'Active Cohort Progression',
  semester_breakdown: 'Students categorized by semester progression',
  no_semester_data: 'No semester cohort breakdown available.',
  students_count: 'Students',
  candidates_awaiting_review: 'Candidates awaiting review',
  view_all: 'View All',
  no_pending_admissions: 'No pending admissions at this moment.',
  review: 'Review',
  recent_receipts: 'Recent Receipts',
  incoming_payments: 'Incoming cashier & bank payments',
  ledger: 'Ledger',
  no_payment_transactions: 'No payment transactions recorded recently.',
  faculty_teaching: 'Faculty Teaching',
  active_schedules: 'Active course schedules & rooms',
  assignments: 'Assignments',
  no_teaching_assignments: 'No teaching assignments allocated.',
  administrative_management: 'Administrative Management Directory',
  quick_navigation: 'Quick navigation to core university management modules and configurations',
  students_directory: 'Student Directory',
  directory_profiles: 'Directory & Profiles',
  admissions_screen: 'Admissions',
  screen_admit: 'Screen & Admit',
  lecturers_staff: 'Lecturers',
  faculty_staff: 'Faculty Staff',
  courses_curriculum: 'Courses',
  curriculum_syllabus: 'Curriculum & Syllabus',
  finance_billing: 'Finance',
  billing_collections: 'Billing & Collections',
  hr_personnel: 'HR',
  personnel_payroll: 'Personnel & Payroll',
  reports_analytics: 'Analytics',
  analytics_insights: 'Analytics & Insights',
  settings_config: 'Settings',
  system_config: 'System Configuration',
  teaching_allocation: 'Teaching',
  course_allocation: 'Course Allocation',
  reports_institutional: 'Reports',
  institutional_data: 'Institutional Data',
  users_roles: 'Users & Roles',
  security_access: 'Security & Access',

  // Students Page
  students_management: 'Students Management',
  students_description: 'Manage and monitor all enrolled student records, academic performance, and fee status.',
  import_students: 'Import Students',
  create_student: 'Create Student',
  total_students: 'Total Students',
  active_enrolled: 'Active Enrolled',
  pending_enrollment: 'Pending Enrollment',
  suspended_status: 'Suspended',
  graduated_status: 'Graduated',
  students_list: 'Students List',
  search_students: 'Search by name, email, matric no, phone...',
  status: 'Status',
  fee_status: 'Fee Status',
  program: 'Program',
  semester_label: 'Semester',
  gender: 'Gender',
  all_statuses: 'All Statuses',
  enrolled_status: 'Enrolled',
  pending_status: 'Pending',
  suspended_label: 'Suspended',
  graduated_label: 'Graduated',
  withdrawn: 'Withdrawn',
  all_fees: 'All Fees',
  paid: 'Paid',
  unpaid: 'Unpaid',
  partial: 'Partial',
  all_programs: 'All Programs',
  all_semesters: 'All Semesters',
  all_genders: 'All Genders',
  male: 'Male',
  female: 'Female',
  delete_student_record: 'Delete Student Record',
  delete_student_description: 'Are you sure you want to delete this student? Their user account will be deactivated.',
  student_deleted_success: 'Student {matric_no} deleted successfully.',
  failed_delete_student: 'Failed to delete student.',
  student_account_activated: 'Student account activated.',
  student_account_suspended: 'Student account suspended.',
  failed_update_status: 'Failed to update student account status.',
  breadcrumb_students: 'Students',
};

export default en;
